import { applyDecorators, Type } from '@nestjs/common';
import { ApiBearerAuth, ApiHeader, ApiOperation, ApiParam, ApiResponse, ApiTags } from '@nestjs/swagger';
import { ApiErrorDto } from '../../common/openapi/api-error.dto';

export function ExpenseApi(operationId: string, response: Type<unknown>, status = 200, mutation = false, hasId = false) {
  return applyDecorators(
    ApiTags('expenses'),
    ApiBearerAuth(),
    ApiOperation({ operationId }),
    ApiHeader({ name: 'X-Request-Id', required: false, description: 'Correlation identifier; generated by the server when omitted.' }),
    ApiResponse({ status, type: response }),
    ...[400, 401, 403, 404, 409, 500].map(code => ApiResponse({ status: code, type: ApiErrorDto })),
    ...(hasId ? [ApiParam({ name: 'id', schema: { type: 'string', format: 'uuid' } })] : []),
    ...(mutation ? [ApiHeader({
      name: 'Idempotency-Key', required: true,
      schema: { type: 'string', pattern: '^[A-Za-z0-9._:-]{8,160}$' },
      description: 'Reuse with the identical payload when retrying an uncertain command.',
    })] : []),
  );
}
