import { applyDecorators, Type } from '@nestjs/common';
import { ApiBearerAuth, ApiHeader, ApiOperation, ApiParam, ApiResponse, ApiTags } from '@nestjs/swagger';
import { ApiErrorDto } from '../../common/openapi/api-error.dto';
import { PaymentCommandResponseDto } from './payment-response.dto';

export function PaymentCommandApi(operationId: string, transition = false,
  response: Type<unknown> = PaymentCommandResponseDto, preview = false) {
  return applyDecorators(
    ApiTags('payment-records'), ApiBearerAuth(),
    ApiOperation({ operationId, description: preview
      ? 'Read-only preview. Commit requires the signed token, explicit confirmation and a command key.'
      : response === PaymentCommandResponseDto
        ? 'Idempotent command. The response reads current payment state; its version belongs to that state, including on replay.'
        : 'Idempotent command using a signed preview. Financial history is preserved.' }),
    ApiParam({ name: 'studentId', schema: { type: 'string', format: 'uuid' } }),
    ...(transition ? [ApiParam({ name: 'paymentRecordId', schema: { type: 'string', format: 'uuid' } })] : []),
    ...(!preview ? [ApiHeader({ name: 'Idempotency-Key', required: true, schema: { type: 'string', pattern: '^[A-Za-z0-9._:-]{8,160}$' } })] : []),
    ApiHeader({ name: 'X-Request-Id', required: false, description: 'Generated by the server if omitted.' }),
    ApiResponse({ status: 201, type: response }),
    ...[400, 401, 403, 404, 409, 422, 500].map(status => ApiResponse({ status, type: ApiErrorDto })),
  );
}
