import 'package:flutter/material.dart';
import 'package:flutter_test/flutter_test.dart';
import 'package:integration_test/integration_test.dart';
import 'package:intl/date_symbol_data_local.dart';
import 'package:magic_music_crm/core/services/magic_crm_service.dart';
import 'package:magic_music_crm/core/widgets/searchable_picker_field.dart';
import 'package:magic_music_crm/features/admin/presentation/widgets/create_lesson_dialog.dart';
import 'package:magic_music_crm/features/admin/presentation/widgets/lesson_editor/lesson_client_funding_fields.dart';
import 'package:magic_music_crm/features/admin/presentation/widgets/lesson_editor/lesson_schedule_section.dart';
import 'package:magic_music_crm/features/admin/presentation/widgets/schedule_widget.dart';
import 'package:magic_music_crm/core/navigation/context_route_state.dart';
import 'live_audit_harness.dart';
void main(){IntegrationTestWidgetsFlutterBinding.ensureInitialized();setUpAll(()=>initializeDateFormatting('ru'));
 for(final role in ['admin','manager','director']){testWidgets('$role lesson funding sources conflicts and history',(tester)async{
  final h=LiveAuditHarness(tester,role,'lesson-funding');await h.initialize(size:const Size(1600,1600));final crm=h.scope.read(magicCrmServiceProvider),id=(h.fixture['lessonIds'] as Map)[role] as String,sid=h.fixture['studentId'] as String,payer=h.fixture['payerId'] as String,sub=h.fixture['subscriptionId'] as String,branch=h.fixture['branchId'] as String;
  Finder key(String k)=>find.byKey(ValueKey(k));Finder editor()=>find.byType(CreateLessonDialog);
  Future<Map<String,dynamic>> read()async=>(await crm.listLessons(lessonId:id,limit:1)).single;
  Future<void> open({bool create=false})async{await tester.pumpWidget(const SizedBox.shrink());await tester.pump();final row=await read();await h.mount(Scaffold(body:Builder(builder:(context)=>FilledButton(onPressed:()=>create?CreateLessonDialog.show(context,initialDate:DateTime.parse(row['scheduled_at']).toLocal(),initialBranchId:branch,initialRoomId:h.fixture['roomId'],clientType:'student',clientId:sid,clientName:'Student0 HTTP test'):CreateLessonDialog.show(context,lesson:row),child:const Text('Открыть редактор')))));await h.tap(find.text('Открыть редактор'));await h.quiet();expect(editor(),findsOneWidget);}
  Future<void> fill(String k,String v)async{await h.tap(key(k));await tester.enterText(key(k),v);await tester.pump();}
  Future<void> select(String k,String label)async{await h.tap(key(k));await h.tap(find.text(label).last);await h.quiet();}
  Map<String,dynamic> funding()=>tester.widget<LessonClientFundingFields>(find.byType(LessonClientFundingFields)).decisions.singleWhere((d)=>d['clientId']==sid);
  Future<void> preview(String reason)async{await fill('lesson-edit-reason',reason);await h.tap(find.descendant(of:editor(),matching:find.widgetWithText(FilledButton,'Рассчитать')));await h.quiet();expect(key('lesson-decision-preview'),findsOneWidget);}
  Future<void> confirm()async{await h.tap(find.widgetWithText(FilledButton,'Подтвердить изменения'));await h.quiet();expect(editor(),findsNothing);}
  await h.check('PAYER','Найти связанного плательщика и загрузить его абонемент',()async{await open();final f=key('lesson-client-payer-$sid');await h.tap(f);await tester.enterText(find.descendant(of:f,matching:find.byType(TextField)),'Student1');await h.quiet();final option=tester.widget<SearchablePickerField>(f);expect(option.onSearch,isNotNull);final ref=(await crm.searchClientRefs(q:'Student1',type:'student',limit:50)).singleWhere((r)=>(r['ref'] as Map)['id']==payer);await h.tap(find.widgetWithText(MenuItemButton,ref['label']).last);await h.quiet();expect(funding()['payerStudentId'],payer);await select('lesson-client-charge-type-$sid','С абонемента');final sf=key('lesson-client-subscription-$sid'),sw=tester.widget<SearchablePickerField>(sf),item=sw.items.singleWhere((i)=>i.id==sub);await select('lesson-client-subscription-$sid',item.label);expect(funding()['subscriptionId'],sub);});
  await h.check('SUB-PREVIEW','Preview смены на абонемент не меняет версию занятия',()async{final before=await read();await preview('AUDIT-PAYER-SUBSCRIPTION');expect((await read())['version'],before['version']);});
  await h.check('SUB-COMMIT','Подтвердить источник и прочитать его в повторно открытой форме',()async{await confirm();await open();expect(funding()['payerStudentId'],payer);expect(funding()['subscriptionId'],sub);expect(funding()['chargeType'],'subscription');});
  await h.check('ACCOUNT-DRAFT','Переключить на личный счёт с ценой, скидкой и доплатой',()async{await select('lesson-client-charge-type-$sid','С личного счёта');expect(funding()['subscriptionId'],isNull);await fill('lesson-client-price-$sid','1500');await select('lesson-client-discount-type-$sid','Процент');await fill('lesson-client-discount-value-$sid','10');await fill('lesson-client-discount-reason-$sid','AUDIT-DISCOUNT');await select('lesson-client-surcharge-type-$sid','Фиксированная сумма');await fill('lesson-client-surcharge-value-$sid','100');await fill('lesson-client-surcharge-reason-$sid','AUDIT-SURCHARGE');expect(funding()['payerStudentId'],payer);});
  await h.check('ACCOUNT-COMMIT','Сохранить новый план и проверить поля после переоткрытия',()async{await preview('AUDIT-PAYER-ACCOUNT');await confirm();await open();final f=funding();expect(f['chargeType'],'personal_account');expect(f['payerStudentId'],payer);expect(f['basePriceMinor'],'150000');expect((f['discount'] as Map)['percentBasisPoints'],1000);expect((f['surcharge'] as Map)['amountMinor'],'10000');expect(f['subscriptionId'],isNull);h.facts.add({'step':h.currentStep,'lessonId':id,'funding':f});});
  await h.check('HISTORY','Раскрыть настоящую историю двух изменений плана расчёта',()async{final row=await read();await tester.pumpWidget(const SizedBox.shrink());await tester.pump();await h.mount(Scaffold(body:ScheduleWidget(initialBranchId:branch,initialViewState:ContextViewState(date:DateTime.parse(row['scheduled_at']).toLocal(),filters:{'view':'day','branchId':branch}))));await h.quiet();await h.tap(key('schedule-lesson-$id').first);await h.quiet();await h.tap(key('lesson-settlement-history'));await h.quiet();expect(find.textContaining('AUDIT-PAYER-SUBSCRIPTION'),findsWidgets);expect(find.textContaining('AUDIT-PAYER-ACCOUNT'),findsWidgets);h.facts.add({'step':h.currentStep,'history':await crm.getLessonSettlementHistory(id)});await h.tap(key('magic-modal-close'));});
  await h.check('CONFLICT','Новая форма показывает реальный конфликт с существующим занятием',()async{await open(create:true);final teacher=key('lesson-teacher-field');await h.tap(teacher);await tester.enterText(find.descendant(of:teacher,matching:find.byType(TextField)),'Teacher0');await h.quiet();await h.tap(find.widgetWithText(MenuItemButton,'Teacher0 HTTP test').last);await h.quiet();await select('lesson-client-charge-type-$sid','С личного счёта');await fill('lesson-client-price-$sid','1000');await h.tap(key('lesson-run-schedule-analyzer'));await h.quiet();expect(key('lesson-conflict-inspector'),findsOneWidget);expect(find.text('Найдены конфликты'),findsWidgets);expect(key('conflict-lesson-$id'),findsWidgets);h.facts.add({'step':h.currentStep,'analysis':tester.widget<LessonScheduleSection>(find.byType(LessonScheduleSection)).model.analysis?.valid});});
  await h.check('CONFLICT-SAVE','Сохранение конфликтного черновика не создаёт второе занятие',()async{final start=h.requests.length;await h.tap(find.widgetWithText(FilledButton,'Создать'));await h.quiet();expect(find.text('Занятие не сохранено'),findsOneWidget);expect(h.requests.skip(start).where((r)=>r['method']=='POST'&&r['path']=='/api/crm/lessons'),isEmpty);await h.tap(find.text('Исправить'));await h.quiet();expect(editor(),findsOneWidget);});
  await h.check('SUGGESTION','Применить предложенное свободное время и подтвердить отсутствие конфликтов',()async{await h.tap(key('lesson-run-schedule-analyzer'));await h.quiet();final suggestions=find.byWidgetPredicate((w)=>w is OutlinedButton&&(w.key as ValueKey?)?.value.toString().startsWith('lesson-suggestion-')==true);await h.tap(suggestions.first);await h.quiet();await h.tap(key('lesson-run-schedule-analyzer'));await h.quiet();expect(tester.widget<LessonScheduleSection>(find.byType(LessonScheduleSection)).model.analysis?.valid,true);expect(find.text('Конфликтов нет'),findsOneWidget);});
  await h.check('CREATE-REPAIRED','Сохранить исправленный черновик и получить одно созданное занятие',()async{final start=h.requests.length;await h.tap(find.widgetWithText(FilledButton,'Создать'));await h.quiet();expect(editor(),findsNothing);expect(h.requests.skip(start).where((r)=>r['method']=='POST'&&r['path']=='/api/crm/lessons'&&r['status']==201).length,1);});await h.finish();
 },timeout:const Timeout(Duration(minutes:8)));}
}
