import 'package:flutter/material.dart';
import 'package:flutter_test/flutter_test.dart';
import 'package:integration_test/integration_test.dart';
import 'package:intl/date_symbol_data_local.dart';
import 'package:magic_music_crm/core/services/magic_crm_service.dart';
import 'package:magic_music_crm/features/crm/presentation/client_card/client_card.dart';
import 'package:magic_music_crm/features/crm/presentation/client_card/subscription_replace_sheet.dart';
import 'package:magic_music_crm/features/crm/presentation/client_card/subscription_cancel_sheet.dart';
import 'live_audit_harness.dart';
void main(){IntegrationTestWidgetsFlutterBinding.ensureInitialized();setUpAll(()=>initializeDateFormatting('ru'));
 for(final role in ['admin','manager','director']){testWidgets('$role used and reserved subscription replacement cancellation',(tester)async{
  final h=LiveAuditHarness(tester,role,'subscription-coverage');await h.initialize(size:const Size(1600,1700));final crm=h.scope.read(magicCrmServiceProvider),f=(h.fixture['cases'] as Map)[role] as Map,sid=f['studentId'] as String,old=f['subscriptionId'] as String;String? current;
  Finder key(String k)=>find.byKey(ValueKey(k));
  Future<void> open()async{await tester.pumpWidget(const SizedBox.shrink());await tester.pump();await h.mount(Scaffold(body:ClientCard(lead:{'id':sid},entityType:'student',routed:true,initialSection:'subscriptions')));await h.quiet();await h.tap(key('client-section-jump-subscriptions'));await h.quiet();}
  Future<void> record()async{final rows=(await crm.getStudentCommerceProjection(sid)).student.subscriptions;h.facts.add({'step':h.currentStep,'rows':rows.map((s)=>s.toLegacyMap(sid)).toList()});}
  await h.check('OPEN','Карточка показывает использованный час и три резерва',()async{await open();final sub=(await crm.getStudentCommerceProjection(sid)).student.subscriptions.singleWhere((s)=>s.id==old);expect(sub.units.used,1);expect(sub.units.reserved,3);expect(key('subscription-replace-$old'),findsOneWidget);await record();});
  await h.check('REPLACE-PREVIEW','Пакет на два часа: два резерва переносятся, третий снимается',()async{await h.tap(key('subscription-replace-$old'));await h.quiet();await h.tap(key('issue-subscription-package-${h.fixture['replacementPackageId']}'));await h.quiet();final p=tester.widget<SubscriptionReplacementForm>(find.byType(SubscriptionReplacementForm)).preview;expect(num.parse(p.usage.usedUnits),1);expect(p.usage.reservedLessonCount,3);expect(p.usage.transferableReservationCount,2);expect(p.usage.releasedReservationCount,1);expect(key('subscription-replace-usage'),findsOneWidget);expect((await crm.getStudentCommerceProjection(sid)).student.subscriptions.singleWhere((s)=>s.id==old).status,'active');h.facts.add({'step':h.currentStep,'used':p.usage.usedUnits,'transferred':p.usage.transferableReservationCount,'released':p.usage.releasedReservationCount});});
  await h.check('REPLACE','Подтверждение создаёт полный новый объём без повторного прихода денег',()async{await h.tap(key('subscription-replace-reason'));await h.tap(find.text('Изменение условий').last);await h.tap(key('subscription-replace-confirmation'));await h.tap(key('subscription-replace-submit'));await h.quiet();expect(find.byType(SubscriptionReplacementForm),findsNothing);final rows=(await crm.getStudentCommerceProjection(sid)).student.subscriptions,sub=rows.singleWhere((s)=>s.status=='active');current=sub.id;expect(sub.units.total,2);expect(sub.units.used,0);expect(sub.units.reserved,2);expect(rows.singleWhere((s)=>s.id==old).units.used,1);await record();});
  await h.check('REOPEN','После переоткрытия новый абонемент сохраняет два резерва',()async{await open();expect(key('subscription-replace-$current'),findsOneWidget);expect(key('subscription-replace-$old'),findsNothing);await record();});
  await h.check('CANCEL-PREVIEW','Отмена показывает связанные будущие занятия и защищённые резервы',()async{await h.tap(key('subscription-cancel-$current'));await h.quiet();final p=tester.widget<SubscriptionCancellationForm>(find.byType(SubscriptionCancellationForm)).preview;expect(p.future.reservedLessonCount,2);expect(num.parse(p.future.reservedUnits),2);expect(p.future.lessons.map((l)=>l.lessonId).toSet(),containsAll((f['lessonIds'] as List).take(2)));expect(p.financial.recommendedRefundMinor,BigInt.zero);expect(key('subscription-cancel-future'),findsOneWidget);});
  await h.check('CANCEL','Отмена снимает оставшиеся резервы и сохраняет историю',()async{await h.tap(key('subscription-cancel-reason'));await h.tap(find.text('Изменилось расписание').last);await h.tap(key('subscription-cancel-confirmation'));await h.tap(key('subscription-cancel-submit'));await h.quiet();expect(find.byType(SubscriptionCancellationForm),findsNothing);final rows=(await crm.getStudentCommerceProjection(sid)).student.subscriptions;expect(rows.singleWhere((s)=>s.id==current).status,'cancelled');expect(rows.singleWhere((s)=>s.id==old).units.used,1);await record();});
  await h.check('FINAL-REOPEN','Карточка после отмены и все три занятия остаются доступными',()async{await open();expect(key('subscription-cancel-$current'),findsNothing);for(final id in f['lessonIds'] as List){final row=(await crm.listLessons(lessonId:id,limit:1)).single;expect(row['id'],id);expect(row['status'],'scheduled');}await record();});await h.finish();
 },timeout:const Timeout(Duration(minutes:6)));}
}
