// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAupMl9pk9dmFm9cNOzF-XCAq6Hb1roeLw',
    appId: '1:1038036512599:android:6b303a532839920dd21812',
    messagingSenderId: '1038036512599',
    projectId: 'magicmusiccrm-42557',
    storageBucket: 'magicmusiccrm-42557.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBctUL95i8Q33ejG1DgnW375kp9sCJ6R5k',
    appId: '1:1038036512599:ios:1697ee3605c5d6e5d21812',
    messagingSenderId: '1038036512599',
    projectId: 'magicmusiccrm-42557',
    storageBucket: 'magicmusiccrm-42557.firebasestorage.app',
    iosBundleId: 'magic.crm',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBctUL95i8Q33ejG1DgnW375kp9sCJ6R5k',
    appId: '1:1038036512599:ios:d32a33026887d369d21812',
    messagingSenderId: '1038036512599',
    projectId: 'magicmusiccrm-42557',
    storageBucket: 'magicmusiccrm-42557.firebasestorage.app',
    iosBundleId: 'com.magicmusiccrm.magicMusicCrm',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAloU3-72eKP8bTMvzVfnD4RldUcGzIPcA',
    appId: '1:1038036512599:web:257296e46e9ddb1ad21812',
    messagingSenderId: '1038036512599',
    projectId: 'magicmusiccrm-42557',
    authDomain: 'magicmusiccrm-42557.firebaseapp.com',
    storageBucket: 'magicmusiccrm-42557.firebasestorage.app',
    measurementId: 'G-KCFRLWQBLV',
  );
}
