import type { PrototypeRole, ScreenDefinition, ScreenKind, ScreenState } from './types'

const allStaff: PrototypeRole[] = ['admin', 'manager', 'director', 'system_admin']
const management: PrototypeRole[] = ['manager', 'director', 'system_admin']
const leadership: PrototypeRole[] = ['director', 'system_admin']
const everyone: PrototypeRole[] = ['client', 'teacher', ...allStaff]

const row = (title: string, subtitle: string, meta?: string, status?: string, target?: string) => ({ title, subtitle, meta, status, target })

function screen(
  id: string,
  group: string,
  title: string,
  description: string,
  roles: PrototypeRole[],
  kind: ScreenKind,
  extra: Partial<ScreenDefinition> = {},
): ScreenDefinition {
  return { id, group, title, description, roles, kind, ...extra }
}

const authScreens: ScreenDefinition[] = [
  screen('auth.login', 'Вход и регистрация', 'Вход', 'Вход по почте или телефону и паролю.', everyone, 'auth', {
    fields: ['Телефон или почта', 'Пароль'],
    actions: [
      { label: 'Войти', target: 'auth.onboarding' },
      { label: 'Забыли пароль?', target: 'auth.reset.request', tone: 'secondary' },
      { label: 'Создать аккаунт', target: 'auth.registration', tone: 'secondary' },
    ],
  }),
  screen('auth.registration', 'Вход и регистрация', 'Регистрация', 'Создание личного аккаунта клиента.', ['client'], 'auth', {
    fields: ['Имя', 'Электронная почта', 'Пароль', 'Повторите пароль'],
    actions: [{ label: 'Зарегистрироваться', target: 'auth.email-code' }, { label: 'Уже есть аккаунт? Войти', target: 'auth.login', tone: 'secondary' }],
  }),
  screen('auth.email-code', 'Вход и регистрация', 'Код из письма', 'Подтверждение адреса электронной почты.', ['client'], 'auth', {
    fields: ['Код из письма'],
    actions: [{ label: 'Подтвердить', target: 'auth.consent' }, { label: 'Отправить код ещё раз', target: 'auth.email-code.sent', tone: 'secondary' }],
  }),
  screen('auth.email-code.sent', 'Вход и регистрация', 'Письмо отправлено', 'Новый код отправлен на указанную почту.', ['client'], 'state', {
    actions: [{ label: 'Ввести код', target: 'auth.email-code' }, { label: 'Изменить почту', target: 'auth.registration', tone: 'secondary' }],
  }),
  screen('auth.reset.request', 'Вход и регистрация', 'Восстановление пароля', 'Запрос кода для смены пароля.', everyone, 'auth', {
    fields: ['Почта или телефон'],
    actions: [{ label: 'Получить код', target: 'auth.reset.confirm' }, { label: 'Назад ко входу', target: 'auth.login', tone: 'secondary' }],
  }),
  screen('auth.reset.confirm', 'Вход и регистрация', 'Новый пароль', 'Подтверждение кода и установка нового пароля.', everyone, 'auth', {
    fields: ['Код из письма', 'Новый пароль', 'Повторите пароль'],
    actions: [{ label: 'Сохранить пароль', target: 'auth.login' }, { label: 'Назад ко входу', target: 'auth.login', tone: 'secondary' }],
  }),
  screen('auth.consent', 'Вход и регистрация', 'Юридические документы', 'Согласие с актуальными условиями использования.', everyone, 'auth', {
    rows: [row('Пользовательское соглашение', 'Редакция от 12.08.2026', undefined, 'Открыть', 'auth.consent.document'), row('Политика конфиденциальности', 'Редакция от 12.08.2026', undefined, 'Открыть', 'auth.consent.document')],
    actions: [{ label: 'Принять и войти', target: 'auth.onboarding' }, { label: 'Назад ко входу', target: 'auth.login', tone: 'secondary' }],
  }),
  screen('auth.consent.document', 'Вход и регистрация', 'Просмотр документа', 'Полный текст юридического документа.', everyone, 'dialog', {
    actions: [{ label: 'Закрыть', target: 'auth.consent' }],
  }),
  screen('auth.onboarding', 'Вход и регистрация', 'Завершение профиля', 'Имя, фамилия и базовые данные профиля.', everyone, 'auth', {
    fields: ['Имя', 'Фамилия'],
    actions: [{ label: 'Продолжить', target: 'overview.main' }, { label: 'Пропустить', target: 'overview.main', tone: 'secondary' }],
  }),
]

const coreScreens: ScreenDefinition[] = [
  screen('overview.main', 'Рабочее пространство', 'Обзор', 'Сводка работы школы и показатели, требующие внимания.', management, 'dashboard', {
    nativeRoute: 'overview',
    metrics: [
      { label: 'Активные ученики', value: '246', detail: '+12 за месяц' },
      { label: 'Новые лиды', value: '7', detail: '3 без ответа' },
      { label: 'Открытые задачи', value: '18', detail: '3 просрочены' },
      { label: 'Конфликты расписания', value: '2', detail: 'Нужна проверка' },
    ],
    actions: [{ label: 'Открыть задачи', target: 'tasks.list' }, { label: 'Проверить конфликты', target: 'schedule.conflicts', tone: 'secondary' }],
  }),
  screen('tasks.list', 'Задачи', 'Задачи', 'Открытые, просроченные и закрытые задачи.', allStaff, 'list', {
    nativeRoute: 'tasks',
    tabs: [{ label: 'Открытые', target: 'tasks.list' }, { label: 'Просроченные', target: 'tasks.overdue' }, { label: 'Закрытые', target: 'tasks.closed' }, { label: 'Календарь', target: 'tasks.calendar' }],
    rows: [row('Позвонить по заявке с сайта', 'Елена Смирнова', 'Сегодня, 12:30', 'Высокий', 'tasks.detail'), row('Согласовать перенос занятия', 'Анна Лебедева', 'Сегодня, 15:00', 'Обычный', 'tasks.detail'), row('Проверить задолженности за август', 'Олег Романов', 'Завтра, 10:00', 'Высокий', 'tasks.detail')],
    actions: [{ label: 'Новая задача', target: 'tasks.create' }],
  }),
  screen('tasks.overdue', 'Задачи', 'Просроченные задачи', 'Задачи, срок которых уже прошёл.', allStaff, 'list', { rows: [row('Позвонить по заявке с сайта', 'Просрочено на 2 часа', 'Елена Смирнова', 'Просрочено', 'tasks.detail')], actions: [{ label: 'Новая задача', target: 'tasks.create' }] }),
  screen('tasks.closed', 'Задачи', 'Закрытые задачи', 'Завершённые задачи и история исполнения.', allStaff, 'list', { rows: [row('Подготовить аудиторию', 'Закрыла Елена Смирнова', '15 августа', 'Готово', 'tasks.detail.closed')] }),
  screen('tasks.calendar', 'Задачи', 'Календарь задач', 'Задачи по датам в месяце.', allStaff, 'schedule', { actions: [{ label: 'Открыть 18 августа', target: 'tasks.calendar.day' }, { label: 'Новая задача', target: 'tasks.create', tone: 'secondary' }] }),
  screen('tasks.calendar.day', 'Задачи', 'Задачи на 18 августа', 'Список задач выбранного дня.', allStaff, 'sheet', { rows: [row('Подготовить аудиторию к концерту', 'Денис Волков', '18:00', 'В работе', 'tasks.detail')], actions: [{ label: 'Закрыть', target: 'tasks.calendar' }] }),
  screen('tasks.detail', 'Задачи', 'Позвонить по заявке с сайта', 'Детали, получатели, срок и история задачи.', allStaff, 'sheet', { rows: [row('Создана', 'Олег Романов', '15 августа, 09:12'), row('Взята в работу', 'Елена Смирнова', '15 августа, 09:25')], actions: [{ label: 'Изменить', target: 'tasks.edit' }, { label: 'Закрыть задачу', target: 'tasks.detail.closed', tone: 'secondary' }] }),
  screen('tasks.detail.closed', 'Задачи', 'Задача закрыта', 'Результат и полная история закрытой задачи.', allStaff, 'sheet', { actions: [{ label: 'Вернуться к задачам', target: 'tasks.closed' }] }),
  screen('tasks.create', 'Задачи', 'Новая задача', 'Срок, приоритет, получатели и напоминание.', allStaff, 'sheet', { fields: ['Название', 'Приоритет', 'Описание', 'Начало', 'Окончание', 'Кому', 'Напомнить'], actions: [{ label: 'Создать', target: 'tasks.list' }, { label: 'Отмена', target: 'tasks.list', tone: 'secondary' }] }),
  screen('tasks.edit', 'Задачи', 'Изменить задачу', 'Редактирование срока, получателей и напоминания.', allStaff, 'sheet', { fields: ['Название', 'Приоритет', 'Описание', 'Начало', 'Окончание', 'Кому', 'Напомнить'], actions: [{ label: 'Сохранить', target: 'tasks.detail' }, { label: 'Отмена', target: 'tasks.detail', tone: 'secondary' }] }),
]

const scheduleScreens: ScreenDefinition[] = [
  screen('schedule.week', 'Расписание', 'Расписание на неделю', 'Сетка занятий по дням и времени.', ['teacher', ...allStaff], 'schedule', { nativeRoute: 'schedule', tabs: [{ label: 'Месяц', target: 'schedule.month' }, { label: 'Неделя', target: 'schedule.week' }, { label: 'День', target: 'schedule.day.rooms' }], actions: [{ label: 'Создать занятие', target: 'schedule.lesson.create' }, { label: 'Фильтры', target: 'schedule.filters', tone: 'secondary' }, { label: 'Поиск', target: 'schedule.search', tone: 'secondary' }] }),
  screen('schedule.month', 'Расписание', 'Расписание на месяц', 'Календарь занятий и загрузки школы.', ['teacher', ...allStaff], 'schedule', { nativeRoute: 'schedule', tabs: [{ label: 'Месяц', target: 'schedule.month' }, { label: 'Неделя', target: 'schedule.week' }, { label: 'День', target: 'schedule.day.rooms' }], actions: [{ label: 'Открыть 18 августа', target: 'schedule.day.rooms' }, { label: 'Создать занятие', target: 'schedule.lesson.create', tone: 'secondary' }] }),
  screen('schedule.day.rooms', 'Расписание', 'День по аудиториям', 'Занятия выбранного дня по аудиториям.', ['teacher', ...allStaff], 'schedule', { nativeRoute: 'schedule', tabs: [{ label: 'Аудитории', target: 'schedule.day.rooms' }, { label: 'Преподаватели', target: 'schedule.day.teachers' }], actions: [{ label: 'Создать занятие', target: 'schedule.lesson.create' }, { label: 'Свободные аудитории', target: 'schedule.free-rooms', tone: 'secondary' }] }),
  screen('schedule.day.teachers', 'Расписание', 'День по преподавателям', 'Занятость преподавателей по часам.', ['teacher', ...allStaff], 'schedule', { nativeRoute: 'schedule', tabs: [{ label: 'Аудитории', target: 'schedule.day.rooms' }, { label: 'Преподаватели', target: 'schedule.day.teachers' }], actions: [{ label: 'Открыть конфликт', target: 'schedule.conflict.inspector' }, { label: 'Графики преподавателей', target: 'settings.schedule.teachers', tone: 'secondary' }] }),
  screen('schedule.search', 'Расписание', 'Поиск занятия', 'Поиск по клиенту, преподавателю, группе и аудитории.', ['teacher', ...allStaff], 'dialog', { fields: ['Клиент, преподаватель или группа', 'Период', 'Филиал'], rows: [row('Матвей Соколов', 'Гитара · Илья Морозов', '15 августа, 10:30', 'Конфликт', 'schedule.lesson.details')], actions: [{ label: 'Закрыть', target: 'schedule.week', tone: 'secondary' }] }),
  screen('schedule.filters', 'Расписание', 'Фильтры расписания', 'Филиал, преподаватель, аудитория и тип занятия.', ['teacher', ...allStaff], 'sheet', { fields: ['Филиал', 'Преподаватель', 'Аудитория', 'Тип занятия'], actions: [{ label: 'Применить', target: 'schedule.week' }, { label: 'Сбросить', target: 'schedule.week', tone: 'secondary' }] }),
  screen('schedule.timezone', 'Расписание', 'Часовой пояс', 'Часовой пояс отображения расписания.', ['teacher', ...allStaff], 'dialog', { fields: ['Часовой пояс'], actions: [{ label: 'Сохранить', target: 'schedule.week' }, { label: 'Отмена', target: 'schedule.week', tone: 'secondary' }] }),
  screen('schedule.lesson.details', 'Расписание', 'Матвей Соколов', 'Детали занятия, участники, аудитория и статус.', ['teacher', ...allStaff], 'sheet', { metrics: [{ label: 'Время', value: '10:30 - 11:30' }, { label: 'Преподаватель', value: 'Илья Морозов' }, { label: 'Аудитория', value: 'Аудитория 1' }, { label: 'Статус', value: 'Конфликт' }], actions: [{ label: 'Перенести или изменить', target: 'schedule.lesson.edit' }, { label: 'Отменить занятие', target: 'schedule.lesson.cancel', tone: 'danger' }] }),
  screen('schedule.lesson.create', 'Расписание', 'Создать занятие', 'Разовое занятие или постоянное расписание.', allStaff, 'form', { tabs: [{ label: 'Разовое занятие', target: 'schedule.lesson.create' }, { label: 'Постоянное расписание', target: 'schedule.recurring.create' }], fields: ['Клиент или группа', 'Преподаватель', 'Филиал', 'Аудитория', 'Дата', 'Начало', 'Продолжительность'], actions: [{ label: 'Проверить и создать', target: 'schedule.lesson.preview' }, { label: 'Отмена', target: 'schedule.week', tone: 'secondary' }] }),
  screen('schedule.lesson.preview', 'Расписание', 'Проверка занятия', 'Результаты единого анализа перед сохранением.', allStaff, 'sheet', { metrics: [{ label: 'Проверок пройдено', value: '4 из 5' }, { label: 'Конфликтов', value: '1' }], rows: [row('Аудитория занята', 'Аудитория 1 · 10:30 - 11:30', 'Совпадает на 30 минут', 'Конфликт', 'schedule.conflict.inspector')], actions: [{ label: 'Подобрать вариант', target: 'schedule.suggestions' }, { label: 'Вернуться к форме', target: 'schedule.lesson.create', tone: 'secondary' }] }),
  screen('schedule.lesson.edit', 'Расписание', 'Изменить занятие', 'Перенос времени, аудитории или преподавателя.', allStaff, 'form', { fields: ['Преподаватель', 'Филиал', 'Аудитория', 'Дата', 'Начало', 'Продолжительность'], actions: [{ label: 'Проверить изменения', target: 'schedule.lesson.preview' }, { label: 'Отмена', target: 'schedule.lesson.details', tone: 'secondary' }] }),
  screen('schedule.lesson.cancel', 'Расписание', 'Отменить занятие?', 'Причина отмены и правило списания.', allStaff, 'dialog', { fields: ['Причина', 'Списание занятия'], actions: [{ label: 'Отменить занятие', target: 'schedule.week', tone: 'danger' }, { label: 'Оставить занятие', target: 'schedule.lesson.details', tone: 'secondary' }] }),
  screen('schedule.recurring.create', 'Расписание', 'План постоянного расписания', 'Наборы дней, период и правила создания занятий.', allStaff, 'form', { fields: ['Клиент или группа', 'Период', 'Дни недели', 'Время', 'Преподаватель', 'Аудитория'], actions: [{ label: 'Добавить другой набор дней', target: 'schedule.recurring.multiple' }, { label: 'Проверить план', target: 'schedule.recurring.preview', tone: 'secondary' }] }),
  screen('schedule.recurring.multiple', 'Расписание', 'Несколько наборов дней', 'Два варианта времени в одном постоянном плане.', allStaff, 'form', { rows: [row('Понедельник и среда', '17:00 · Анна Лебедева', 'Аудитория 2', 'Готово'), row('Суббота', '12:00 · Анна Лебедева', 'Аудитория 3', 'Готово')], actions: [{ label: 'Проверить план', target: 'schedule.recurring.preview' }, { label: 'Добавить строку', target: 'schedule.recurring.multiple', tone: 'secondary' }] }),
  screen('schedule.recurring.preview', 'Расписание', 'Проверка постоянного плана', 'Будущие занятия, конфликты и предлагаемые замены.', allStaff, 'sheet', { metrics: [{ label: 'Будущих занятий', value: '16' }, { label: 'Без конфликтов', value: '14' }, { label: 'Требуют решения', value: '2' }], rows: [row('19 августа, 17:00', 'Аудитория 2 занята', 'Найдены 3 варианта', 'Конфликт', 'schedule.conflict.inspector'), row('26 августа, 17:00', 'Преподаватель занят', 'Найдены 2 варианта', 'Конфликт', 'schedule.conflict.inspector')], actions: [{ label: 'Создать без конфликтов', target: 'schedule.recurring.created' }, { label: 'Исправить план', target: 'schedule.recurring.create', tone: 'secondary' }] }),
  screen('schedule.recurring.created', 'Расписание', 'Постоянное расписание создано', 'Занятия без конфликтов добавлены в расписание.', allStaff, 'state', { actions: [{ label: 'Открыть расписание', target: 'schedule.week' }, { label: 'Открыть карточку клиента', target: 'clients.student.card', tone: 'secondary' }] }),
  screen('schedule.conflicts', 'Расписание', 'Конфликты расписания', 'Сгруппированные пересечения по типу и времени.', management, 'list', { rows: [row('Аудитория занята', '2 занятия · Аудитория 1', '15 августа, 10:30', '2 конфликта', 'schedule.conflict.inspector'), row('Преподаватель занят', 'Анна Лебедева', '19 августа, 17:00', '1 конфликт', 'schedule.conflict.inspector')], actions: [{ label: 'Обновить анализ', target: 'schedule.conflicts' }] }),
  screen('schedule.conflict.inspector', 'Расписание', 'Проверка конфликта', 'Участники пересечения и способы исправления.', allStaff, 'sheet', { rows: [row('Матвей Соколов', '10:30 - 11:30 · Аудитория 1', 'Илья Морозов', 'Новое занятие'), row('София Крылова', '10:00 - 11:00 · Аудитория 1', 'Мария Орлова', 'Уже в расписании')], actions: [{ label: 'Показать варианты', target: 'schedule.suggestions' }, { label: 'Вернуться к занятию', target: 'schedule.lesson.preview', tone: 'secondary' }] }),
  screen('schedule.suggestions', 'Расписание', 'Варианты без конфликта', 'Свободные аудитории, время и преподаватели с оценкой удобства.', allStaff, 'list', { rows: [row('Аудитория 3 в то же время', 'Без переноса · тот же преподаватель', 'Оценка 96 из 100', 'Лучший вариант', 'schedule.suggestion.confirm'), row('11:30 в аудитории 1', 'Перенос на 60 минут', 'Оценка 88 из 100', 'Подходит', 'schedule.suggestion.confirm'), row('Елена Власова в 10:30', 'Та же специализация · аудитория 2', 'Оценка 81 из 100', 'Подходит', 'schedule.suggestion.confirm')] }),
  screen('schedule.suggestion.confirm', 'Расписание', 'Применить вариант?', 'Подтверждение выбранной замены до сохранения.', allStaff, 'dialog', { actions: [{ label: 'Применить', target: 'schedule.lesson.preview' }, { label: 'Назад к вариантам', target: 'schedule.suggestions', tone: 'secondary' }] }),
  screen('schedule.free-rooms', 'Расписание', 'Свободные аудитории', 'Аудитории, доступные в выбранное время.', allStaff, 'sheet', { rows: [row('Аудитория 3', 'Садовая · 6 мест', '10:30 - 11:30', 'Свободна', 'schedule.suggestion.confirm'), row('Студия', 'Садовая · 12 мест', '10:30 - 11:30', 'Свободна', 'schedule.suggestion.confirm')] }),
]

const clientManagementScreens: ScreenDefinition[] = [
  screen('clients.leads', 'Клиенты', 'Лиды', 'Воронка лидов по этапам.', allStaff, 'board', { nativeRoute: 'clients', tabs: [{ label: 'Лиды', target: 'clients.leads' }, { label: 'Ученики', target: 'clients.students' }], rows: [row('София Крылова', '+7 915 208-44-63', 'Сайт · Садовая', 'В процессе', 'clients.lead.card'), row('Павел Титов', '+7 926 122-09-17', 'Рекомендация · Петроградская', 'Пробный урок', 'clients.lead.card')], actions: [{ label: 'Новый контакт', target: 'clients.lead.create' }, { label: 'Фильтры', target: 'clients.filters', tone: 'secondary' }] }),
  screen('clients.students', 'Клиенты', 'Ученики', 'Ученики школы по этапам обучения.', allStaff, 'board', { nativeRoute: 'clients', tabs: [{ label: 'Лиды', target: 'clients.leads' }, { label: 'Ученики', target: 'clients.students' }], rows: [row('Алиса Воронцова', '+7 999 418-22-17', 'Фортепиано · Садовая', 'Обучается', 'clients.student.card'), row('Матвей Соколов', '+7 921 744-30-08', 'Гитара · Садовая', 'Нужна оплата', 'clients.student.card')], actions: [{ label: 'Новый ученик', target: 'clients.student.create' }, { label: 'Фильтры', target: 'clients.filters', tone: 'secondary' }] }),
  screen('clients.filters', 'Клиенты', 'Фильтры клиентов', 'Этап, филиал, направление и ответственный.', allStaff, 'sheet', { fields: ['Этап', 'Филиал', 'Направление', 'Ответственный'], actions: [{ label: 'Применить', target: 'clients.leads' }, { label: 'Сбросить', target: 'clients.leads', tone: 'secondary' }] }),
  screen('clients.lead.create', 'Клиенты', 'Новый контакт', 'Создание лида в воронке.', allStaff, 'dialog', { fields: ['Имя', 'Фамилия', 'Телефон', 'Филиал', 'Этап воронки', 'Рекламный источник'], actions: [{ label: 'Создать', target: 'clients.lead.card' }, { label: 'Отмена', target: 'clients.leads', tone: 'secondary' }] }),
  screen('clients.student.create', 'Клиенты', 'Новый ученик', 'Создание карточки ученика.', allStaff, 'dialog', { fields: ['Имя', 'Фамилия', 'Телефон', 'Филиал', 'Этап', 'Рекламный источник'], actions: [{ label: 'Создать', target: 'clients.student.card' }, { label: 'Отмена', target: 'clients.students', tone: 'secondary' }] }),
  screen('clients.lead.card', 'Карточка клиента', 'София Крылова', 'Единая прокручиваемая карточка лида.', allStaff, 'card', { nativeRoute: 'clientCard', tabs: [{ label: 'Обзор', target: 'clients.lead.card' }, { label: 'Контакты', target: 'clients.contacts' }, { label: 'Занятия', target: 'clients.lessons' }, { label: 'Абонементы', target: 'clients.subscriptions' }, { label: 'Прогресс', target: 'clients.progress' }, { label: 'Задачи и история', target: 'clients.history' }, { label: 'Документы', target: 'clients.documents' }], metrics: [{ label: 'Тип', value: 'Лид' }, { label: 'Этап', value: 'В процессе' }, { label: 'Филиал', value: 'Садовая' }, { label: 'Ответственный', value: 'Елена Смирнова' }], actions: [{ label: 'Сохранить', target: 'clients.lead.card' }, { label: 'Прикрепить к ученику', target: 'clients.link-student', tone: 'secondary' }] }),
  screen('clients.student.card', 'Карточка клиента', 'Алиса Воронцова', 'Единая прокручиваемая карточка ученика.', allStaff, 'card', { nativeRoute: 'clientCard', tabs: [{ label: 'Обзор', target: 'clients.student.card' }, { label: 'Контакты', target: 'clients.contacts' }, { label: 'Занятия', target: 'clients.lessons' }, { label: 'Абонементы', target: 'clients.subscriptions' }, { label: 'Прогресс', target: 'clients.progress' }, { label: 'Оплаты', target: 'clients.payments' }, { label: 'Задачи и история', target: 'clients.history' }, { label: 'Документы', target: 'clients.documents' }], metrics: [{ label: 'Тип', value: 'Ученик' }, { label: 'Баланс', value: '0 ₽' }, { label: 'Филиал', value: 'Садовая' }, { label: 'Направление', value: 'Фортепиано' }], actions: [{ label: 'Сохранить', target: 'clients.student.card' }, { label: 'Открыть в расписании', target: 'schedule.week', tone: 'secondary' }] }),
  screen('clients.contacts', 'Карточка клиента', 'Контакты', 'Семья, контактные лица и доступ в приложение.', allStaff, 'card', { rows: [row('Наталья Воронцова', 'Мама · +7 916 401-33-12', 'Основной контакт', 'Связана', 'clients.contact.edit')], actions: [{ label: 'Добавить контактное лицо', target: 'clients.contact.create' }, { label: 'Пригласить в приложение', target: 'clients.access.invite', tone: 'secondary' }] }),
  screen('clients.contact.create', 'Карточка клиента', 'Добавить контактное лицо', 'Имя, родство и способы связи.', allStaff, 'dialog', { fields: ['Имя', 'Кем приходится', 'Телефон', 'Почта'], actions: [{ label: 'Добавить', target: 'clients.contacts' }, { label: 'Отмена', target: 'clients.contacts', tone: 'secondary' }] }),
  screen('clients.contact.edit', 'Карточка клиента', 'Изменить контакт', 'Контактные данные и признак основного контакта.', allStaff, 'dialog', { fields: ['Имя', 'Кем приходится', 'Телефон', 'Почта', 'Основной контакт'], actions: [{ label: 'Сохранить', target: 'clients.contacts' }, { label: 'Отмена', target: 'clients.contacts', tone: 'secondary' }] }),
  screen('clients.access.invite', 'Карточка клиента', 'Доступ в приложение', 'Выдача клиенту почты и временного пароля.', leadership, 'dialog', { fields: ['Электронная почта', 'Временный пароль'], notes: ['Данные доступа видны только директору и системному администратору.'], actions: [{ label: 'Выдать доступ', target: 'clients.contacts' }, { label: 'Отмена', target: 'clients.contacts', tone: 'secondary' }] }),
  screen('clients.link-student', 'Карточка клиента', 'Связать с учеником?', 'Поиск существующего ученика и подтверждение связи.', allStaff, 'dialog', { fields: ['Поиск ученика'], rows: [row('Алиса Воронцова', '+7 999 418-22-17', 'Садовая', 'Ученик')], actions: [{ label: 'Связать', target: 'clients.student.card' }, { label: 'Отмена', target: 'clients.lead.card', tone: 'secondary' }] }),
  screen('clients.lessons', 'Карточка клиента', 'Занятия', 'Постоянный план и календарь занятий клиента.', allStaff, 'card', { rows: [row('Понедельник и среда', '17:00 · Анна Лебедева', 'Аудитория 2', 'Действует', 'clients.recurring.detail')], actions: [{ label: 'Добавить расписание', target: 'schedule.recurring.create' }, { label: 'Календарь клиента', target: 'schedule.week', tone: 'secondary' }] }),
  screen('clients.recurring.detail', 'Карточка клиента', 'Постоянное расписание', 'Строки плана, созданные занятия и период действия.', allStaff, 'sheet', { rows: [row('Пн и Ср, 17:00', 'Анна Лебедева · Аудитория 2', '19.08.2026 - 30.11.2026', 'Действует')], actions: [{ label: 'Изменить план', target: 'schedule.recurring.create' }, { label: 'Завершить', target: 'clients.recurring.finish', tone: 'danger' }] }),
  screen('clients.recurring.finish', 'Карточка клиента', 'Завершить расписание?', 'Дата завершения и влияние на будущие занятия.', allStaff, 'dialog', { fields: ['Дата завершения'], actions: [{ label: 'Завершить', target: 'clients.lessons', tone: 'danger' }, { label: 'Отмена', target: 'clients.recurring.detail', tone: 'secondary' }] }),
  screen('clients.subscriptions', 'Карточка клиента', 'Абонементы', 'Выданные пакеты, остатки и связанные оплаты.', allStaff, 'card', { metrics: [{ label: 'Всего', value: '8' }, { label: 'Использовано', value: '4' }, { label: 'Зарезервировано', value: '0' }, { label: 'Доступно', value: '4' }], rows: [row('Развитие', '8 занятий · до 28.09.2026', '16 500 ₽', 'Действует', 'clients.subscription.detail')], actions: [{ label: 'Выдать абонемент', target: 'clients.subscription.issue' }] }),
  screen('clients.subscription.issue', 'Карточка клиента', 'Выдать абонемент', 'Пакет, стоимость, срок и привязка оплаты.', allStaff, 'sheet', { fields: ['Абонемент', 'Дата начала', 'Стоимость', 'Оплачено', 'Способ оплаты'], actions: [{ label: 'Рассчитать', target: 'clients.subscription.preview' }, { label: 'Отмена', target: 'clients.subscriptions', tone: 'secondary' }] }),
  screen('clients.subscription.preview', 'Карточка клиента', 'Проверка абонемента', 'Предварительный расчёт остатков и оплаты.', allStaff, 'sheet', { metrics: [{ label: 'Занятий', value: '8' }, { label: 'Стоимость', value: '16 500 ₽' }, { label: 'Оплачено', value: '16 500 ₽' }, { label: 'Доступно', value: '8' }], actions: [{ label: 'Выдать абонемент', target: 'clients.subscription.detail' }, { label: 'Назад', target: 'clients.subscription.issue', tone: 'secondary' }] }),
  screen('clients.subscription.detail', 'Карточка клиента', 'Абонемент «Развитие»', 'Баланс, занятия, оплаты и история изменений.', allStaff, 'sheet', { metrics: [{ label: 'Всего', value: '8' }, { label: 'Использовано', value: '4' }, { label: 'Оплачено', value: '8' }, { label: 'Долг', value: 'Нет' }], actions: [{ label: 'Изменить и пересчитать', target: 'clients.subscription.replace' }, { label: 'Отменить абонемент', target: 'clients.subscription.cancel', tone: 'danger' }] }),
  screen('clients.subscription.replace', 'Карточка клиента', 'Изменить абонемент', 'Безопасный пересчёт выданного абонемента.', leadership, 'sheet', { fields: ['Новый пакет', 'Дата изменения', 'Причина'], metrics: [{ label: 'Было доступно', value: '4 занятия' }, { label: 'Станет доступно', value: '8 занятий' }, { label: 'Доплата', value: '7 600 ₽' }], actions: [{ label: 'Рассчитать', target: 'clients.subscription.replace.preview' }, { label: 'Отмена', target: 'clients.subscription.detail', tone: 'secondary' }] }),
  screen('clients.subscription.replace.preview', 'Карточка клиента', 'Подтвердить пересчёт', 'Сравнение текущего и нового состояния.', leadership, 'dialog', { actions: [{ label: 'Подтвердить изменение', target: 'clients.subscription.detail' }, { label: 'Назад', target: 'clients.subscription.replace', tone: 'secondary' }] }),
  screen('clients.subscription.cancel', 'Карточка клиента', 'Отменить абонемент', 'Причина, будущие занятия и финансовый результат.', leadership, 'sheet', { fields: ['Причина отмены', 'Дата отмены'], metrics: [{ label: 'Будущие занятия', value: '4' }, { label: 'Покрыто резервом', value: '0' }, { label: 'К возврату', value: '8 250 ₽' }], actions: [{ label: 'Продолжить', target: 'clients.subscription.cancel.preview' }, { label: 'Назад', target: 'clients.subscription.detail', tone: 'secondary' }] }),
  screen('clients.subscription.cancel.preview', 'Карточка клиента', 'Подтвердить отмену', 'Итог отмены и возврата до фиксации.', leadership, 'dialog', { actions: [{ label: 'Отменить абонемент', target: 'clients.subscriptions', tone: 'danger' }, { label: 'Назад', target: 'clients.subscription.cancel', tone: 'secondary' }] }),
  screen('clients.payments', 'Карточка клиента', 'Оплаты', 'Личный счёт и неизменяемая финансовая история.', leadership, 'card', { metrics: [{ label: 'Личный счёт', value: '0 ₽' }, { label: 'Оплачено', value: '16 500 ₽' }, { label: 'Ожидает', value: '0 ₽' }, { label: 'Долг', value: '0 ₽' }], rows: [row('16 500 ₽', '14.08.2026 · Безналичная оплата', 'Абонемент «Развитие»', 'Проведено', 'clients.payment.detail')], actions: [{ label: 'Добавить оплату', target: 'clients.payment.create' }] }),
  screen('clients.payment.create', 'Карточка клиента', 'Добавить оплату', 'Сумма, способ, принявший сотрудник и назначение.', leadership, 'sheet', { fields: ['Сумма', 'Способ оплаты', 'Дата', 'Филиал', 'Принял', 'Абонемент'], actions: [{ label: 'Добавить оплату', target: 'clients.payments' }, { label: 'Отмена', target: 'clients.payments', tone: 'secondary' }] }),
  screen('clients.payment.detail', 'Карточка клиента', 'Оплата 16 500 ₽', 'Реквизиты операции и последующие исправления.', leadership, 'sheet', { metrics: [{ label: 'Сумма', value: '16 500 ₽' }, { label: 'Дата', value: '14.08.2026' }, { label: 'Способ', value: 'Безналичная оплата' }, { label: 'Статус', value: 'Проведено' }], actions: [{ label: 'Изменить и пересчитать', target: 'clients.payment.correct' }, { label: 'Закрыть', target: 'clients.payments', tone: 'secondary' }] }),
  screen('clients.payment.correct', 'Карточка клиента', 'Исправить оплату', 'Новая корректирующая операция с сохранением исходной записи.', leadership, 'sheet', { fields: ['Сумма', 'Способ оплаты', 'Дата', 'Статус', 'Причина'], actions: [{ label: 'Рассчитать', target: 'clients.payment.correct.preview' }, { label: 'Отмена', target: 'clients.payment.detail', tone: 'secondary' }] }),
  screen('clients.payment.correct.preview', 'Карточка клиента', 'Проверка исправления', 'Сравнение исходной и корректирующей операций.', leadership, 'dialog', { metrics: [{ label: 'Было', value: '16 500 ₽' }, { label: 'Станет', value: '15 500 ₽' }, { label: 'Разница', value: '-1 000 ₽' }], fields: ['Подтверждаю исправление и пересчёт'], actions: [{ label: 'Подтвердить', target: 'clients.payment.detail' }, { label: 'Назад', target: 'clients.payment.correct', tone: 'secondary' }] }),
  screen('clients.progress', 'Карточка клиента', 'Прогресс и домашние задания', 'Направления, заметки преподавателей и задания.', allStaff, 'card', { rows: [row('Гаммы до мажор', 'Назначила Анна Лебедева', 'Срок 21 августа', 'Назначено', 'clients.homework.detail')], actions: [{ label: 'Назначить домашнее задание', target: 'clients.homework.create' }] }),
  screen('clients.homework.create', 'Карточка клиента', 'Новое домашнее задание', 'Описание, срок и прикреплённые материалы.', allStaff, 'sheet', { fields: ['Название', 'Описание', 'Срок', 'Материалы'], actions: [{ label: 'Назначить', target: 'clients.progress' }, { label: 'Отмена', target: 'clients.progress', tone: 'secondary' }] }),
  screen('clients.homework.detail', 'Карточка клиента', 'Гаммы до мажор', 'Задание, материалы и ответ ученика.', allStaff, 'sheet', { rows: [row('Ответ ученика', 'Аудиозапись · 2:14', '20 августа, 18:05', 'Сдано')], actions: [{ label: 'Отметить проверенным', target: 'clients.progress' }, { label: 'Закрыть', target: 'clients.progress', tone: 'secondary' }] }),
  screen('clients.history', 'Карточка клиента', 'Задачи, комментарии и история', 'Рабочая история клиента в одном разделе.', allStaff, 'card', { tabs: [{ label: 'Задачи', target: 'clients.history' }, { label: 'Комментарии', target: 'clients.comments' }, { label: 'История', target: 'clients.audit' }], rows: [row('Позвонить по оплате', 'Елена Смирнова', 'Сегодня, 16:00', 'Открыта', 'tasks.detail')], actions: [{ label: 'Новая задача', target: 'tasks.create' }] }),
  screen('clients.comments', 'Карточка клиента', 'Комментарии', 'Внутренние комментарии сотрудников.', allStaff, 'card', { rows: [row('Елена Смирнова', 'Семья просит занятия после 17:00.', '15 августа, 11:28')], fields: ['Новый комментарий'], actions: [{ label: 'Добавить комментарий', target: 'clients.comments' }] }),
  screen('clients.audit', 'Карточка клиента', 'История изменений', 'Действия сотрудников и изменения карточки.', allStaff, 'list', { rows: [row('Изменён этап воронки', 'Елена Смирнова', '15 августа, 10:42'), row('Добавлен телефон', 'Олег Романов', '14 августа, 16:18')] }),
  screen('clients.documents', 'Карточка клиента', 'Документы', 'Поддерживаемые документы появятся в этом разделе.', allStaff, 'state', { state: 'empty' }),
  screen('clients.archive', 'Карточка клиента', 'Архивировать клиента?', 'Причина закрытия и предварительная проверка связей.', leadership, 'dialog', { fields: ['Причина'], actions: [{ label: 'Проверить связи', target: 'clients.archive.preview' }, { label: 'Отмена', target: 'clients.student.card', tone: 'secondary' }] }),
  screen('clients.archive.preview', 'Карточка клиента', 'Проверка архивации', 'Связи, которые сохранятся после закрытия карточки.', leadership, 'sheet', { metrics: [{ label: 'Занятия', value: '32' }, { label: 'Оплаты', value: '4' }, { label: 'Комментарии', value: '6' }], actions: [{ label: 'Архивировать', target: 'clients.students', tone: 'danger' }, { label: 'Назад', target: 'clients.archive', tone: 'secondary' }] }),
]

const portalScreens: ScreenDefinition[] = [
  screen('client.lessons.upcoming', 'Кабинет клиента', 'Занятия', 'Ближайшие занятия клиента.', ['client'], 'list', { nativeRoute: 'clientLessons', tabs: [{ label: 'Предстоящие', target: 'client.lessons.upcoming' }, { label: 'История', target: 'client.lessons.history' }, { label: 'Задания', target: 'client.homework' }], rows: [row('Фортепиано', 'Анна Лебедева · Аудитория 2', '18 августа, 17:00', 'Запланировано', 'client.lesson.details')] }),
  screen('client.lessons.history', 'Кабинет клиента', 'История занятий', 'Прошедшие и отменённые занятия.', ['client'], 'list', { rows: [row('Фортепиано', 'Анна Лебедева', '14 августа, 17:00', 'Проведено', 'client.lesson.details')] }),
  screen('client.lesson.details', 'Кабинет клиента', 'Занятие по фортепиано', 'Время, преподаватель, аудитория и домашнее задание.', ['client'], 'sheet', { metrics: [{ label: 'Дата', value: '18 августа' }, { label: 'Время', value: '17:00 - 18:00' }, { label: 'Преподаватель', value: 'Анна Лебедева' }, { label: 'Аудитория', value: 'Аудитория 2' }], actions: [{ label: 'Открыть задание', target: 'client.homework.detail' }, { label: 'Закрыть', target: 'client.lessons.upcoming', tone: 'secondary' }] }),
  screen('client.homework', 'Кабинет клиента', 'Домашние задания', 'Назначенные, сданные и проверенные задания.', ['client'], 'list', { rows: [row('Гаммы до мажор', 'Фортепиано · Анна Лебедева', 'Срок 21 августа', 'Назначено', 'client.homework.detail'), row('Этюд №3', 'Фортепиано · Анна Лебедева', 'Сдано 14 августа', 'Проверено', 'client.homework.detail')] }),
  screen('client.homework.detail', 'Кабинет клиента', 'Гаммы до мажор', 'Описание задания и материалы преподавателя.', ['client'], 'card', { notes: ['Сыграть в спокойном темпе обеими руками.'], rows: [row('Пример исполнения', 'Аудиозапись · 1:48', 'Анна Лебедева', 'Файл')], actions: [{ label: 'Сдать работу', target: 'client.homework.submit' }, { label: 'Назад к заданиям', target: 'client.homework', tone: 'secondary' }] }),
  screen('client.homework.submit', 'Кабинет клиента', 'Сдать домашнее задание', 'Комментарий и файл ответа.', ['client'], 'sheet', { fields: ['Комментарий', 'Фото, документ, аудио или видео'], actions: [{ label: 'Сдать', target: 'client.homework.submitted' }, { label: 'Отмена', target: 'client.homework.detail', tone: 'secondary' }] }),
  screen('client.homework.submitted', 'Кабинет клиента', 'Работа сдана', 'Ответ отправлен преподавателю на проверку.', ['client'], 'state', { actions: [{ label: 'Вернуться к заданиям', target: 'client.homework' }] }),
  screen('client.subscription', 'Кабинет клиента', 'Абонемент', 'Состояние текущего абонемента.', ['client'], 'card', { nativeRoute: 'clientSubscription', tabs: [{ label: 'Абонемент', target: 'client.subscription' }, { label: 'Оплаты', target: 'client.payments' }], metrics: [{ label: 'Всего', value: '8 занятий' }, { label: 'Оплачено', value: '8' }, { label: 'Доступно', value: '4' }, { label: 'Следующий платёж', value: '28 сентября' }] }),
  screen('client.payments', 'Кабинет клиента', 'Оплаты', 'История оплат клиента.', ['client'], 'list', { tabs: [{ label: 'Абонемент', target: 'client.subscription' }, { label: 'Оплаты', target: 'client.payments' }], rows: [row('16 500 ₽', '14 августа · Безналичная оплата', 'Абонемент «Развитие»', 'Проведено', 'client.payment.details')] }),
  screen('client.payment.details', 'Кабинет клиента', 'Оплата 16 500 ₽', 'Состав и статус оплаты.', ['client'], 'sheet', { metrics: [{ label: 'Сумма', value: '16 500 ₽' }, { label: 'Дата', value: '14 августа' }, { label: 'Способ', value: 'Безналичная оплата' }, { label: 'Статус', value: 'Проведено' }], actions: [{ label: 'Закрыть', target: 'client.payments' }] }),
  screen('client.profile', 'Кабинет клиента', 'Профиль', 'Личные данные и настройки аккаунта.', ['client'], 'card', { nativeRoute: 'clientProfile', rows: [row('Способы входа', 'Пароль и код из письма', undefined, 'Открыть', 'profile.auth-methods'), row('Юридические документы', 'Условия и политика', undefined, 'Открыть', 'profile.legal'), row('Удаление аккаунта', 'Запрос и статус удаления', undefined, 'Открыть', 'profile.delete')], actions: [{ label: 'Изменить профиль', target: 'profile.edit' }] }),
]

const teacherScreens: ScreenDefinition[] = [
  screen('teacher.schedule', 'Кабинет преподавателя', 'Расписание', 'Назначенные преподавателю занятия.', ['teacher'], 'schedule', { nativeRoute: 'schedule', actions: [{ label: 'Открыть занятие', target: 'teacher.lesson.details' }] }),
  screen('teacher.students', 'Кабинет преподавателя', 'Ученики', 'Ученики, назначенные преподавателю.', ['teacher'], 'list', { nativeRoute: 'teacherStudents', rows: [row('Алиса Воронцова', 'Фортепиано', 'Следующее занятие 18 августа', 'Активна', 'teacher.student.card'), row('Вера Мельникова', 'Скрипка', 'Следующее занятие 20 августа', 'Активна', 'teacher.student.card')] }),
  screen('teacher.student.card', 'Кабинет преподавателя', 'Алиса Воронцова', 'Учебный контекст, занятия и задания ученика.', ['teacher'], 'card', { tabs: [{ label: 'Занятия', target: 'teacher.student.card' }, { label: 'Домашние задания', target: 'teacher.student.homework' }, { label: 'Прогресс', target: 'teacher.student.progress' }], rows: [row('18 августа, 17:00', 'Фортепиано · Аудитория 2', '60 минут', 'Запланировано', 'teacher.lesson.details')] }),
  screen('teacher.student.homework', 'Кабинет преподавателя', 'Домашние задания ученика', 'Назначение и проверка работ.', ['teacher'], 'list', { rows: [row('Гаммы до мажор', 'Срок 21 августа', 'Ответ ещё не отправлен', 'Назначено', 'clients.homework.detail')], actions: [{ label: 'Назначить задание', target: 'clients.homework.create' }] }),
  screen('teacher.student.progress', 'Кабинет преподавателя', 'Прогресс ученика', 'Заметки и учебная динамика.', ['teacher'], 'card', { fields: ['Заметка преподавателя'], actions: [{ label: 'Сохранить заметку', target: 'teacher.student.progress' }] }),
  screen('teacher.lesson.details', 'Кабинет преподавателя', 'Занятие с Алисой Воронцовой', 'Детали занятия и учебные действия.', ['teacher'], 'sheet', { metrics: [{ label: 'Дата', value: '18 августа' }, { label: 'Время', value: '17:00 - 18:00' }, { label: 'Аудитория', value: 'Аудитория 2' }], actions: [{ label: 'Назначить домашнее задание', target: 'clients.homework.create' }, { label: 'Открыть ученика', target: 'teacher.student.card', tone: 'secondary' }] }),
]

const analyticsScreens: ScreenDefinition[] = [
  screen('analytics.overview', 'Аналитика', 'Аналитика', 'Единая сводка по занятиям, клиентам, задачам и финансам.', management, 'analytics', { nativeRoute: 'analytics', tabs: [{ label: 'Обзор', target: 'analytics.overview' }, { label: 'Журналы', target: 'analytics.activity' }], metrics: [{ label: 'Завершённые занятия', value: '93,9%' }, { label: 'Новые лиды', value: '7' }, { label: 'Открытые задачи', value: '18' }, { label: 'Выручка', value: '940 200 ₽' }], actions: [{ label: 'Выгрузить таблицу', target: 'analytics.export' }] }),
  screen('analytics.activity', 'Аналитика', 'Журнал действий', 'Действия сотрудников в системе.', management, 'analytics', { tabs: [{ label: 'Действия', target: 'analytics.activity' }, { label: 'Финансовые операции', target: 'analytics.finance' }, { label: 'Расчёты преподавателей', target: 'analytics.teachers' }], rows: [row('Изменено занятие', 'Елена Смирнова', '15 августа, 10:42', 'Расписание'), row('Добавлена оплата', 'Олег Романов', '15 августа, 10:18', 'Финансы')] }),
  screen('analytics.finance', 'Аналитика', 'Финансовые операции', 'Доходы, расходы и исправления операций.', leadership, 'analytics', { rows: [row('Оплата 16 500 ₽', 'Алиса Воронцова', '14 августа', 'Приход', 'clients.payment.detail'), row('Аренда 120 000 ₽', 'Садовая', '1 августа', 'Расход', 'finance.expense.detail')], actions: [{ label: 'Добавить расход', target: 'finance.expense.create' }] }),
  screen('analytics.teachers', 'Аналитика', 'Расчёты преподавателей', 'Начисления по проведённым занятиям.', leadership, 'analytics', { rows: [row('Анна Лебедева', '42 занятия', '1 - 15 августа', '63 000 ₽', 'analytics.teacher.detail'), row('Илья Морозов', '38 занятий', '1 - 15 августа', '57 000 ₽', 'analytics.teacher.detail')] }),
  screen('analytics.teacher.detail', 'Аналитика', 'Расчёт Анны Лебедевой', 'Занятия, ставка и итог начисления.', leadership, 'sheet', { metrics: [{ label: 'Занятий', value: '42' }, { label: 'Ставка', value: '1 500 ₽' }, { label: 'Итого', value: '63 000 ₽' }], actions: [{ label: 'Закрыть', target: 'analytics.teachers' }] }),
  screen('analytics.export', 'Аналитика', 'Выгрузка отчёта', 'Период, филиал и формат файла.', management, 'dialog', { fields: ['Период', 'Филиал', 'Формат'], actions: [{ label: 'Сформировать', target: 'analytics.export.ready' }, { label: 'Отмена', target: 'analytics.overview', tone: 'secondary' }] }),
  screen('analytics.export.ready', 'Аналитика', 'Отчёт готов', 'Файл подготовлен для сохранения.', management, 'state', { actions: [{ label: 'Вернуться к аналитике', target: 'analytics.overview' }] }),
  screen('finance.expense.create', 'Финансы', 'Добавить расход', 'Сумма, категория, филиал и комментарий.', leadership, 'sheet', { fields: ['Сумма', 'Категория', 'Дата', 'Филиал', 'Комментарий'], actions: [{ label: 'Добавить', target: 'analytics.finance' }, { label: 'Отмена', target: 'analytics.finance', tone: 'secondary' }] }),
  screen('finance.expense.detail', 'Финансы', 'Расход 120 000 ₽', 'Реквизиты расхода и история изменений.', leadership, 'sheet', { metrics: [{ label: 'Категория', value: 'Аренда' }, { label: 'Филиал', value: 'Садовая' }, { label: 'Дата', value: '1 августа' }], actions: [{ label: 'Изменить', target: 'finance.expense.edit' }, { label: 'Удалить', target: 'finance.expense.delete', tone: 'danger' }] }),
  screen('finance.expense.edit', 'Финансы', 'Изменить расход', 'Сумма, категория или комментарий.', leadership, 'sheet', { fields: ['Сумма', 'Категория', 'Дата', 'Филиал', 'Комментарий'], actions: [{ label: 'Сохранить', target: 'finance.expense.detail' }, { label: 'Отмена', target: 'finance.expense.detail', tone: 'secondary' }] }),
  screen('finance.expense.delete', 'Финансы', 'Удалить расход?', 'Подтверждение удаления ошибочно созданного расхода.', leadership, 'dialog', { actions: [{ label: 'Удалить', target: 'analytics.finance', tone: 'danger' }, { label: 'Отмена', target: 'finance.expense.detail', tone: 'secondary' }] }),
]

const settingsScreens: ScreenDefinition[] = [
  screen('settings.root', 'Настройки системы', 'Настройки системы', 'Шесть действующих областей настроек.', management, 'settings', { nativeRoute: 'settings', rows: [row('Организация', 'Филиалы и справочники', undefined, 'Открыть', 'settings.organization'), row('Расписание', 'Часы, графики и группы', undefined, 'Открыть', 'settings.schedule'), row('Клиенты', 'Поля, категории и воронка', undefined, 'Открыть', 'settings.crm'), row('Продажи и оплаты', 'Каталог абонементов', undefined, 'Открыть', 'settings.sales'), row('Пользователи и доступы', 'Доступы, сотрудники и преподаватели', undefined, 'Открыть', 'settings.users'), row('Данные и обслуживание', 'Качество и запросы на удаление', undefined, 'Открыть', 'settings.data')] }),
  screen('settings.organization', 'Настройки системы', 'Организация', 'Филиалы и общие справочники.', management, 'settings', { tabs: [{ label: 'Филиалы', target: 'settings.organization' }, { label: 'Справочники', target: 'settings.catalogs' }], rows: [row('Садовая', 'Пн - Сб, 09:00 - 21:00', '5 аудиторий', 'Действует', 'settings.branch.detail'), row('Петроградская', 'Пн - Вс, 10:00 - 20:00', '3 аудитории', 'Действует', 'settings.branch.detail')], actions: [{ label: 'Новый филиал', target: 'settings.branch.create' }] }),
  screen('settings.branch.create', 'Настройки системы', 'Новый филиал', 'Название, адрес, часы и дисциплины.', leadership, 'dialog', { fields: ['Название', 'Адрес', 'Рабочие часы', 'Дисциплины', 'Аудитории'], actions: [{ label: 'Сохранить', target: 'settings.organization' }, { label: 'Отмена', target: 'settings.organization', tone: 'secondary' }] }),
  screen('settings.branch.detail', 'Настройки системы', 'Филиал «Садовая»', 'Адрес, рабочие часы, дисциплины и аудитории.', management, 'dialog', { fields: ['Название', 'Адрес', 'Рабочие часы'], rows: [row('Аудитория 1', '6 мест · Фортепиано', undefined, 'Действует', 'settings.room.detail'), row('Аудитория 2', '4 места · Вокал', undefined, 'Действует', 'settings.room.detail')], actions: [{ label: 'Сохранить', target: 'settings.organization' }, { label: 'Архивировать', target: 'settings.branch.archive', tone: 'danger' }] }),
  screen('settings.branch.archive', 'Настройки системы', 'Архивировать филиал?', 'Проверка действующих связей перед закрытием.', leadership, 'sheet', { metrics: [{ label: 'Активные занятия', value: '18' }, { label: 'Ученики', value: '94' }, { label: 'Сотрудники', value: '7' }], actions: [{ label: 'Открыть блокировки', target: 'settings.branch.blockers' }, { label: 'Отмена', target: 'settings.branch.detail', tone: 'secondary' }] }),
  screen('settings.branch.blockers', 'Настройки системы', 'Филиал нельзя архивировать', 'Активные связи, которые нужно завершить.', leadership, 'state', { state: 'error', rows: [row('18 будущих занятий', 'Завершите или перенесите занятия', undefined, 'Блокирует', 'schedule.week')], actions: [{ label: 'Вернуться к филиалу', target: 'settings.branch.detail' }] }),
  screen('settings.catalogs', 'Настройки системы', 'Справочники', 'Направления, источники, статусы и причины.', management, 'settings', { rows: [row('Направления', 'Фортепиано, вокал, гитара и ещё 5', undefined, '8 значений', 'settings.catalog.detail'), row('Рекламные источники', 'Сайт, рекомендация, социальные сети', undefined, '6 значений', 'settings.catalog.detail'), row('Причины отмены', 'Правила списания занятий', undefined, '5 значений', 'settings.catalog.detail')], actions: [{ label: 'Новый справочник', target: 'settings.catalog.create' }] }),
  screen('settings.catalog.detail', 'Настройки системы', 'Направления', 'Значения справочника и архив.', management, 'list', { rows: [row('Фортепиано', 'Цвет: золотой', undefined, 'Действует', 'settings.catalog.item'), row('Вокал', 'Цвет: синий', undefined, 'Действует', 'settings.catalog.item')], actions: [{ label: 'Добавить значение', target: 'settings.catalog.item' }, { label: 'Показать архив', target: 'settings.catalog.archive', tone: 'secondary' }] }),
  screen('settings.catalog.create', 'Настройки системы', 'Новый справочник', 'Название и область применения.', leadership, 'dialog', { fields: ['Название', 'Область применения'], actions: [{ label: 'Создать', target: 'settings.catalogs' }, { label: 'Отмена', target: 'settings.catalogs', tone: 'secondary' }] }),
  screen('settings.catalog.item', 'Настройки системы', 'Значение справочника', 'Название, порядок и цветовое обозначение.', leadership, 'dialog', { fields: ['Название', 'Порядок', 'Цвет'], actions: [{ label: 'Сохранить', target: 'settings.catalog.detail' }, { label: 'Архивировать', target: 'settings.catalog.archive', tone: 'danger' }] }),
  screen('settings.catalog.archive', 'Настройки системы', 'Архив справочника', 'Завершённые значения и возможность восстановления.', management, 'list', { rows: [row('Листовка', 'Рекламный источник', 'Архивирован 1 июня', 'В архиве', 'settings.catalog.item')] }),
  screen('settings.room.detail', 'Настройки системы', 'Аудитория 1', 'Название, вместимость и доступные дисциплины.', management, 'dialog', { fields: ['Название', 'Вместимость', 'Дисциплины'], actions: [{ label: 'Сохранить', target: 'settings.branch.detail' }, { label: 'Архивировать', target: 'settings.room.archive', tone: 'danger' }] }),
  screen('settings.room.archive', 'Настройки системы', 'Архивировать аудиторию?', 'Проверка будущих занятий в аудитории.', leadership, 'dialog', { actions: [{ label: 'Проверить связи', target: 'settings.room.blockers' }, { label: 'Отмена', target: 'settings.room.detail', tone: 'secondary' }] }),
  screen('settings.room.blockers', 'Настройки системы', 'Аудитория используется', 'Будущие занятия блокируют архивацию.', leadership, 'state', { state: 'error', rows: [row('12 будущих занятий', 'Аудитория 1', 'До 30 сентября', 'Блокирует', 'schedule.week')], actions: [{ label: 'Вернуться', target: 'settings.room.detail' }] }),
  screen('settings.schedule', 'Настройки системы', 'Расписание', 'Рабочие часы, доступность и учебные группы.', management, 'settings', { tabs: [{ label: 'Часы филиалов', target: 'settings.schedule.branches' }, { label: 'Графики преподавателей', target: 'settings.schedule.teachers' }, { label: 'Группы', target: 'settings.groups' }] }),
  screen('settings.schedule.branches', 'Настройки системы', 'Часы работы филиалов', 'Рабочие интервалы по дням недели.', management, 'settings', { rows: [row('Садовая', 'Пн - Сб, 09:00 - 21:00', undefined, 'Настроено', 'settings.branch.detail'), row('Петроградская', 'Пн - Вс, 10:00 - 20:00', undefined, 'Настроено', 'settings.branch.detail')] }),
  screen('settings.schedule.teachers', 'Настройки системы', 'Графики преподавателей', 'Доступность преподавателей по филиалам.', management, 'settings', { rows: [row('Анна Лебедева', 'Пн, Ср, Пт · 12:00 - 20:00', 'Садовая', 'Активен', 'settings.teacher.schedule'), row('Илья Морозов', 'Вт, Чт, Сб · 10:00 - 18:00', 'Садовая', 'Активен', 'settings.teacher.schedule')] }),
  screen('settings.teacher.schedule', 'Настройки системы', 'График Анны Лебедевой', 'Рабочие интервалы и филиалы преподавателя.', management, 'sheet', { fields: ['Филиал', 'Дни недели', 'Начало', 'Окончание'], actions: [{ label: 'Сохранить', target: 'settings.schedule.teachers' }, { label: 'Отмена', target: 'settings.schedule.teachers', tone: 'secondary' }] }),
  screen('settings.groups', 'Настройки системы', 'Учебные группы', 'Состав, преподаватель и постоянное расписание групп.', management, 'list', { rows: [row('Группа «Ритм»', 'Сольфеджио · Мария Орлова', '8 участников', 'Действует', 'settings.group.detail')], actions: [{ label: 'Новая группа', target: 'settings.group.create' }] }),
  screen('settings.group.create', 'Настройки системы', 'Новая группа', 'Название, направление, преподаватель и участники.', management, 'dialog', { fields: ['Название', 'Направление', 'Преподаватель', 'Филиал'], actions: [{ label: 'Создать', target: 'settings.group.detail' }, { label: 'Отмена', target: 'settings.groups', tone: 'secondary' }] }),
  screen('settings.group.detail', 'Настройки системы', 'Группа «Ритм»', 'Участники и постоянное расписание группы.', management, 'dialog', { rows: [row('Матвей Соколов', 'Ученик', undefined, 'Активен'), row('София Крылова', 'Ученик', undefined, 'Активна')], actions: [{ label: 'Участники', target: 'settings.group.participants' }, { label: 'Добавить расписание', target: 'schedule.recurring.create', tone: 'secondary' }, { label: 'Завершить группу', target: 'settings.group.finish', tone: 'danger' }] }),
  screen('settings.group.participants', 'Настройки системы', 'Участники группы', 'Добавление и исключение учеников.', management, 'sheet', { fields: ['Поиск ученика'], rows: [row('Матвей Соколов', 'Абонемент действует', undefined, 'Участник'), row('София Крылова', 'Нет активного абонемента', undefined, 'Нужна проверка')], actions: [{ label: 'Сохранить состав', target: 'settings.group.detail' }] }),
  screen('settings.group.finish', 'Настройки системы', 'Завершить группу?', 'Дата завершения и влияние на будущие занятия.', leadership, 'dialog', { fields: ['Дата завершения'], actions: [{ label: 'Завершить', target: 'settings.groups', tone: 'danger' }, { label: 'Отмена', target: 'settings.group.detail', tone: 'secondary' }] }),
  screen('settings.crm', 'Настройки системы', 'Клиенты', 'Структура карточек, поля, категории и воронка.', management, 'settings', { rows: [row('Структура и видимость полей', 'Поля лида и ученика', undefined, 'Настроено', 'settings.crm.fields'), row('Категории', 'Группы пользовательских полей', undefined, '6 категорий', 'settings.crm.categories'), row('Значения списков и справочников', 'Источники, статусы и причины', undefined, 'Открыть', 'settings.crm.lists'), row('Воронка лидов', 'Этапы и переходы', undefined, '5 этапов', 'settings.crm.pipeline')], actions: [{ label: 'Сохранить черновик', target: 'settings.crm.draft' }, { label: 'Проверить и опубликовать', target: 'settings.crm.publish', tone: 'secondary' }] }),
  screen('settings.crm.fields', 'Настройки системы', 'Структура и видимость полей', 'Системные и пользовательские поля карточки.', management, 'settings', { rows: [row('Имя', 'Системное поле · Лид и ученик', undefined, 'Обязательно'), row('Рекламный источник', 'Справочник · Лид', undefined, 'Обязательно'), row('Возраст', 'Число · Ученик', undefined, 'Необязательно')] }),
  screen('settings.crm.categories', 'Настройки системы', 'Категории полей', 'Группировка дополнительных полей карточки.', management, 'settings', { rows: [row('Обучение', '4 поля', undefined, 'Видима'), row('Маркетинг', '3 поля', undefined, 'Видима')] }),
  screen('settings.crm.lists', 'Настройки системы', 'Значения списков', 'Значения пользовательских списков и справочников.', management, 'settings', { rows: [row('Рекламный источник', 'Лид и ученик · системный справочник', undefined, '6 значений'), row('Типы списания занятия', 'Название и цвет', undefined, '5 значений')] }),
  screen('settings.crm.pipeline', 'Настройки системы', 'Воронка лидов', 'Этапы, порядок и доступные переходы.', management, 'settings', { rows: [row('Новый', 'Первый этап', undefined, 'Действует'), row('В процессе', 'После первого контакта', undefined, 'Действует'), row('Пробный урок', 'Назначено пробное занятие', undefined, 'Действует'), row('Обучается', 'Лид стал учеником', undefined, 'Действует')] }),
  screen('settings.crm.draft', 'Настройки системы', 'Черновик сохранён', 'Изменения ещё не видны сотрудникам.', management, 'state', { actions: [{ label: 'Вернуться к настройкам', target: 'settings.crm' }, { label: 'Проверить публикацию', target: 'settings.crm.publish', tone: 'secondary' }] }),
  screen('settings.crm.publish', 'Настройки системы', 'Проверка публикации', 'Затронутые экраны и возможные проблемы.', leadership, 'dialog', { notes: ['Затронутые экраны: карточка лида, карточка ученика, создание клиента.'], actions: [{ label: 'Опубликовать', target: 'settings.crm.published' }, { label: 'Назад', target: 'settings.crm', tone: 'secondary' }] }),
  screen('settings.crm.published', 'Настройки системы', 'Настройки опубликованы', 'Новая конфигурация доступна сотрудникам.', leadership, 'state', { actions: [{ label: 'Вернуться к настройкам', target: 'settings.crm' }] }),
  screen('settings.sales', 'Настройки системы', 'Продажи и оплаты', 'Каталог абонементов.', management, 'settings', { rows: [row('Старт', '4 занятия · срок 30 дней', '8 900 ₽', 'Действует', 'settings.package.detail'), row('Развитие', '8 занятий · срок 45 дней', '16 500 ₽', 'Действует', 'settings.package.detail')], actions: [{ label: 'Новый абонемент', target: 'settings.package.create' }, { label: 'Показать архив', target: 'settings.package.archive', tone: 'secondary' }] }),
  screen('settings.package.create', 'Настройки системы', 'Новый абонемент', 'Название, количество занятий, цена и срок.', leadership, 'dialog', { fields: ['Название', 'Количество занятий', 'Цена', 'Срок действия'], actions: [{ label: 'Создать', target: 'settings.sales' }, { label: 'Отмена', target: 'settings.sales', tone: 'secondary' }] }),
  screen('settings.package.detail', 'Настройки системы', 'Абонемент «Развитие»', 'Параметры пакета и действующие выдачи.', management, 'dialog', { fields: ['Название', 'Количество занятий', 'Цена', 'Срок действия'], metrics: [{ label: 'Действующих выдач', value: '64' }], actions: [{ label: 'Сохранить', target: 'settings.sales' }, { label: 'Архивировать', target: 'settings.package.archive.confirm', tone: 'danger' }] }),
  screen('settings.package.archive.confirm', 'Настройки системы', 'Архивировать абонемент?', 'Новые выдачи будут недоступны, текущие сохранятся.', leadership, 'dialog', { actions: [{ label: 'Архивировать', target: 'settings.package.archive', tone: 'danger' }, { label: 'Отмена', target: 'settings.package.detail', tone: 'secondary' }] }),
  screen('settings.package.archive', 'Настройки системы', 'Архив абонементов', 'Пакеты, недоступные для новых выдач.', management, 'list', { rows: [row('Пробный', '1 занятие · 7 дней', '1 500 ₽', 'В архиве', 'settings.package.detail')] }),
  screen('settings.users', 'Настройки системы', 'Пользователи и доступы', 'Доступы, сотрудники и преподаватели.', leadership, 'settings', { nativeRoute: 'settings', tabs: [{ label: 'Доступы', target: 'settings.users' }, { label: 'Сотрудники', target: 'settings.staff' }, { label: 'Преподаватели', target: 'settings.teachers' }], rows: [row('Елена Смирнова', 'Администратор · elena@magicmusic.ru', 'Последний вход сегодня', 'Активен', 'settings.user.detail'), row('Олег Романов', 'Управляющий · o.romanov@magicmusic.ru', 'Последний вход вчера', 'Активен', 'settings.user.detail')], actions: [{ label: 'Новый пользователь', target: 'settings.user.create' }] }),
  screen('settings.user.create', 'Настройки системы', 'Новый пользователь', 'Сотрудник или преподаватель и данные доступа.', leadership, 'dialog', { fields: ['Тип пользователя', 'Имя', 'Фамилия', 'Телефон', 'Электронная почта', 'Временный пароль', 'Роль'], notes: ['Почта и актуальный пароль доступны только директору и системному администратору.'], actions: [{ label: 'Создать', target: 'settings.user.detail' }, { label: 'Отмена', target: 'settings.users', tone: 'secondary' }] }),
  screen('settings.user.detail', 'Настройки системы', 'Елена Смирнова', 'Учётная запись, роль, доступы и уведомления.', leadership, 'dialog', { metrics: [{ label: 'Роль', value: 'Администратор' }, { label: 'Почта', value: 'elena@magicmusic.ru' }, { label: 'Пароль', value: '••••••••' }, { label: 'Состояние', value: 'Активен' }], actions: [{ label: 'Изменить роль', target: 'settings.user.role' }, { label: 'Показать пароль', target: 'settings.user.password', tone: 'secondary' }, { label: 'Уведомления', target: 'settings.user.notifications', tone: 'secondary' }] }),
  screen('settings.user.password', 'Настройки системы', 'Актуальные данные входа', 'Почта и текущий пароль пользователя.', leadership, 'dialog', { metrics: [{ label: 'Почта', value: 'elena@magicmusic.ru' }, { label: 'Пароль', value: 'Magic-2026-91' }], notes: ['Эти данные видны только директору и системному администратору.'], actions: [{ label: 'Закрыть', target: 'settings.user.detail' }] }),
  screen('settings.user.role', 'Настройки системы', 'Изменить роль', 'Роль, область доступа и причина изменения.', leadership, 'sheet', { fields: ['Роль', 'Область доступа', 'Причина изменения', 'Подтверждаю сброс'], actions: [{ label: 'Сохранить роль', target: 'settings.user.detail' }, { label: 'Отмена', target: 'settings.user.detail', tone: 'secondary' }] }),
  screen('settings.user.notifications', 'Настройки системы', 'Настройки уведомлений', 'Каналы уведомлений для выбранной роли.', leadership, 'dialog', { fields: ['Задачи', 'Расписание', 'Оплаты', 'Системные события'], actions: [{ label: 'Сохранить', target: 'settings.user.detail' }, { label: 'Отмена', target: 'settings.user.detail', tone: 'secondary' }] }),
  screen('settings.staff', 'Настройки системы', 'Сотрудники', 'Сотрудники школы и их рабочие данные.', leadership, 'list', { rows: [row('Елена Смирнова', 'Администратор', 'Садовая', 'Работает', 'settings.staff.detail'), row('Олег Романов', 'Управляющий', 'Вся школа', 'Работает', 'settings.staff.detail')], actions: [{ label: 'Новый сотрудник', target: 'settings.staff.create' }] }),
  screen('settings.staff.create', 'Настройки системы', 'Новый сотрудник', 'Личные, рабочие и учётные данные.', leadership, 'dialog', { fields: ['Имя', 'Фамилия', 'Телефон', 'Должность', 'Филиал', 'Почта', 'Временный пароль'], actions: [{ label: 'Создать', target: 'settings.staff.detail' }, { label: 'Отмена', target: 'settings.staff', tone: 'secondary' }] }),
  screen('settings.staff.detail', 'Настройки системы', 'Елена Смирнова', 'Должность, филиал, доступ и жизненный цикл.', leadership, 'dialog', { fields: ['Имя', 'Фамилия', 'Телефон', 'Должность', 'Филиал'], actions: [{ label: 'Сохранить', target: 'settings.staff' }, { label: 'Доступ', target: 'settings.user.detail', tone: 'secondary' }, { label: 'Уволить', target: 'settings.person.lifecycle', tone: 'danger' }] }),
  screen('settings.teachers', 'Настройки системы', 'Преподаватели', 'Преподаватели, направления и ставки.', leadership, 'list', { rows: [row('Анна Лебедева', 'Фортепиано · Скрипка', '1 500 ₽ за занятие', 'Работает', 'settings.teacher.detail'), row('Илья Морозов', 'Гитара', '1 500 ₽ за занятие', 'Работает', 'settings.teacher.detail')], actions: [{ label: 'Новый преподаватель', target: 'settings.teacher.create' }] }),
  screen('settings.teacher.create', 'Настройки системы', 'Новый преподаватель', 'Личные данные, направления, ставка и доступ.', leadership, 'dialog', { fields: ['Имя', 'Фамилия', 'Телефон', 'Направления', 'Филиал', 'Ставка', 'Почта', 'Временный пароль'], actions: [{ label: 'Создать', target: 'settings.teacher.detail' }, { label: 'Отмена', target: 'settings.teachers', tone: 'secondary' }] }),
  screen('settings.teacher.detail', 'Настройки системы', 'Анна Лебедева', 'Рабочие данные, направления, ставка и доступ.', leadership, 'dialog', { metrics: [{ label: 'Ставка', value: '1 500 ₽' }, { label: 'Направления', value: 'Фортепиано, скрипка' }, { label: 'Филиал', value: 'Садовая' }], actions: [{ label: 'Сохранить', target: 'settings.teachers' }, { label: 'Доступ', target: 'settings.user.detail', tone: 'secondary' }, { label: 'Прекратить работу', target: 'settings.person.lifecycle', tone: 'danger' }] }),
  screen('settings.person.lifecycle', 'Настройки системы', 'Изменить состояние сотрудника', 'Дата, причина и проверка связанных данных.', leadership, 'dialog', { fields: ['Новое состояние', 'Дата', 'Причина'], actions: [{ label: 'Проверить связи', target: 'settings.person.lifecycle.preview' }, { label: 'Отмена', target: 'settings.staff.detail', tone: 'secondary' }] }),
  screen('settings.person.lifecycle.preview', 'Настройки системы', 'Проверка связей', 'Занятия, задачи и расчёты сотрудника.', leadership, 'sheet', { metrics: [{ label: 'Будущие занятия', value: '12' }, { label: 'Открытые задачи', value: '3' }, { label: 'Расчёты', value: '1 период' }], actions: [{ label: 'Подтвердить', target: 'settings.staff' }, { label: 'Назад', target: 'settings.person.lifecycle', tone: 'secondary' }] }),
  screen('settings.data', 'Настройки системы', 'Данные и обслуживание', 'Качество данных и запросы на удаление.', leadership, 'settings', { tabs: [{ label: 'Качество данных', target: 'settings.data.quality' }, { label: 'Запросы на удаление', target: 'settings.data.deletions' }] }),
  screen('settings.data.quality', 'Настройки системы', 'Качество данных', 'Телефоны для проверки и возможные дубликаты.', leadership, 'settings', { metrics: [{ label: 'Телефоны на проверку', value: '3' }, { label: 'Возможные дубликаты', value: '2' }], rows: [row('+7 999 41', 'Неполный номер · София Крылова', undefined, 'Нужна проверка', 'settings.data.phone'), row('София Крылова / Софья Крылова', 'Совпадают телефон и филиал', undefined, 'Возможный дубликат', 'settings.data.duplicate')], actions: [{ label: 'Проверить сейчас', target: 'settings.data.quality' }] }),
  screen('settings.data.phone', 'Настройки системы', 'Проверка телефона', 'Исходное значение и исправленный номер.', leadership, 'dialog', { fields: ['Исходный номер', 'Исправленный номер'], actions: [{ label: 'Сохранить', target: 'settings.data.quality' }, { label: 'Отмена', target: 'settings.data.quality', tone: 'secondary' }] }),
  screen('settings.data.duplicate', 'Настройки системы', 'Возможный дубликат', 'Сравнение двух карточек перед объединением.', leadership, 'sheet', { rows: [row('София Крылова', '+7 915 208-44-63', 'Садовая', 'Основная карточка'), row('Софья Крылова', '+7 915 208-44-63', 'Садовая', 'Дубликат')], actions: [{ label: 'Объединить', target: 'settings.data.merge.confirm' }, { label: 'Не дубликат', target: 'settings.data.quality', tone: 'secondary' }] }),
  screen('settings.data.merge.confirm', 'Настройки системы', 'Объединить лидов?', 'Перенос данных в основную карточку.', leadership, 'dialog', { actions: [{ label: 'Объединить', target: 'settings.data.quality' }, { label: 'Отмена', target: 'settings.data.duplicate', tone: 'secondary' }] }),
  screen('settings.data.deletions', 'Настройки системы', 'Запросы на удаление', 'Запросы пользователей и их состояния.', leadership, 'list', { rows: [row('Иван Петров', 'Запрос от 14 августа', 'Срок обработки 28 августа', 'На проверке', 'settings.data.deletion.detail')] }),
  screen('settings.data.deletion.detail', 'Настройки системы', 'Запрос на удаление', 'Состав данных и блокировки удаления.', leadership, 'sheet', { metrics: [{ label: 'Профиль', value: '1' }, { label: 'Занятия', value: '18' }, { label: 'Оплаты', value: '3' }], actions: [{ label: 'Начать проверку', target: 'settings.data.deletion.preview' }, { label: 'Отклонить', target: 'settings.data.deletions', tone: 'danger' }] }),
  screen('settings.data.deletion.preview', 'Настройки системы', 'Проверка удаления', 'Данные, которые будут обезличены, и сохраняемая история.', leadership, 'sheet', { notes: ['Финансовая и учебная история сохраняется в обезличенном виде.'], actions: [{ label: 'Подтвердить обработку', target: 'settings.data.deletions' }, { label: 'Назад', target: 'settings.data.deletion.detail', tone: 'secondary' }] }),
]

const chatAndProfileScreens: ScreenDefinition[] = [
  screen('chat.inbox', 'Чат', 'Чат', 'Обращения лидов, учеников и отдельные чаты.', everyone, 'chat', { nativeRoute: 'chat', tabs: [{ label: 'Лиды', target: 'chat.inbox' }, { label: 'Ученики', target: 'chat.students' }, { label: 'Архив', target: 'chat.archive' }], actions: [{ label: 'Создать чат или канал', target: 'chat.create.menu' }], rows: [row('София Крылова', 'Можно перенести занятие на пятницу?', '10:42', '2 новых', 'chat.dialog'), row('Никита Орлов', 'Хочу записаться на гитару', '09:18', 'Новое', 'chat.dialog')] }),
  screen('chat.students', 'Чат', 'Чаты учеников', 'Обращения действующих учеников и родителей.', everyone, 'chat', { tabs: [{ label: 'Лиды', target: 'chat.inbox' }, { label: 'Ученики', target: 'chat.students' }, { label: 'Архив', target: 'chat.archive' }], rows: [row('Алиса Воронцова', 'Задание отправлено преподавателю', '11:04', 'Прочитано', 'chat.dialog'), row('Родители группы «Ритм»', 'Концерт состоится в 18:00', 'Вчера', 'Группа', 'chat.group')] }),
  screen('chat.archive', 'Чат', 'Архив чатов', 'Завершённые и скрытые обращения.', everyone, 'chat', { tabs: [{ label: 'Лиды', target: 'chat.inbox' }, { label: 'Ученики', target: 'chat.students' }, { label: 'Архив', target: 'chat.archive' }], rows: [row('Павел Титов', 'Спасибо, всё получилось', '12 августа', 'В архиве', 'chat.dialog')] }),
  screen('chat.dialog', 'Чат', 'София Крылова', 'Личное обращение клиента.', everyone, 'chat', { rows: [row('София Крылова', 'Можно перенести занятие на пятницу?', '10:42'), row('Елена Смирнова', 'Да, предложу свободное время.', '10:44')], actions: [{ label: 'Информация', target: 'chat.info', tone: 'secondary' }, { label: 'Поиск по чату', target: 'chat.search', tone: 'secondary' }, { label: 'Прикрепить файл', target: 'chat.file', tone: 'secondary' }] }),
  screen('chat.search', 'Чат', 'Поиск по чату', 'Поиск сообщения внутри открытого диалога.', everyone, 'chat', { actions: [{ label: 'Закрыть поиск', target: 'chat.dialog', tone: 'secondary' }] }),
  screen('chat.info', 'Чат', 'Информация о чате', 'Профиль, уведомления, материалы и действия.', everyone, 'sheet', { tabs: [{ label: 'Медиа', target: 'chat.info' }, { label: 'Файлы', target: 'chat.info.files' }, { label: 'Ссылки', target: 'chat.info.links' }], rows: [row('София Крылова', 'Клиент', '+7 915 208-44-63', 'Открыть карточку', 'clients.lead.card')], actions: [{ label: 'Архивировать чат', target: 'chat.archive' }, { label: 'Закрыть', target: 'chat.dialog', tone: 'secondary' }] }),
  screen('chat.info.files', 'Чат', 'Файлы чата', 'Документы и другие вложения диалога.', everyone, 'sheet', { tabs: [{ label: 'Медиа', target: 'chat.info' }, { label: 'Файлы', target: 'chat.info.files' }, { label: 'Ссылки', target: 'chat.info.links' }], rows: [row('Расписание_август.pdf', 'Елена Смирнова · 14 августа', '1,2 МБ', 'Файл')] , actions: [{ label: 'Закрыть', target: 'chat.dialog', tone: 'secondary' }] }),
  screen('chat.info.links', 'Чат', 'Ссылки чата', 'Ссылки из сообщений диалога.', everyone, 'sheet', { tabs: [{ label: 'Медиа', target: 'chat.info' }, { label: 'Файлы', target: 'chat.info.files' }, { label: 'Ссылки', target: 'chat.info.links' }], rows: [row('Материалы к занятию', 'Отправлено 12 августа', 'magicmusic.ru', 'Ссылка')], actions: [{ label: 'Закрыть', target: 'chat.dialog', tone: 'secondary' }] }),
  screen('chat.file', 'Чат', 'Отправить файл', 'Предпросмотр вложения и подпись.', everyone, 'dialog', { fields: ['Файл', 'Подпись'], actions: [{ label: 'Отправить', target: 'chat.dialog' }, { label: 'Отмена', target: 'chat.dialog', tone: 'secondary' }] }),
  screen('chat.create.menu', 'Чат', 'Создать чат или канал', 'Выбор типа нового пространства.', allStaff, 'dialog', { actions: [{ label: 'Новая группа', target: 'chat.group.create' }, { label: 'Новый канал', target: 'chat.channel.create', tone: 'secondary' }, { label: 'Отмена', target: 'chat.inbox', tone: 'secondary' }] }),
  screen('chat.group.create', 'Чат', 'Новая группа', 'Название и участники группового чата.', allStaff, 'dialog', { fields: ['Название группы', 'Участники'], actions: [{ label: 'Создать', target: 'chat.group' }, { label: 'Отмена', target: 'chat.inbox', tone: 'secondary' }] }),
  screen('chat.group', 'Чат', 'Команда филиала', 'Групповой чат сотрудников.', allStaff, 'chat', { actions: [{ label: 'Информация', target: 'chat.group.edit', tone: 'secondary' }, { label: 'Поиск по чату', target: 'chat.search', tone: 'secondary' }, { label: 'Прикрепить файл', target: 'chat.file', tone: 'secondary' }] }),
  screen('chat.group.edit', 'Чат', 'Информация о группе', 'Название, участники, уведомления и права.', allStaff, 'sheet', { fields: ['Название'], rows: [row('Елена Смирнова', 'Администратор', 'В сети', 'Участник'), row('Олег Романов', 'Директор', 'Был недавно', 'Владелец')], actions: [{ label: 'Сохранить', target: 'chat.group' }, { label: 'Закрыть', target: 'chat.group', tone: 'secondary' }] }),
  screen('chat.channel.create', 'Чат', 'Новый канал', 'Название, описание и право публикации.', allStaff, 'dialog', { fields: ['Название канала', 'Описание', 'Кто может публиковать'], actions: [{ label: 'Создать', target: 'chat.channel' }, { label: 'Отмена', target: 'chat.inbox', tone: 'secondary' }] }),
  screen('chat.channel', 'Чат', 'Объявления', 'Канал школы для важных публикаций.', everyone, 'chat', { actions: [{ label: 'Информация', target: 'chat.channel.edit', tone: 'secondary' }, { label: 'Поиск по каналу', target: 'chat.search', tone: 'secondary' }] }),
  screen('chat.channel.edit', 'Чат', 'Информация о канале', 'Описание, участники и право публикации.', allStaff, 'sheet', { fields: ['Название', 'Описание', 'Кто может публиковать'], actions: [{ label: 'Сохранить', target: 'chat.channel' }, { label: 'Закрыть', target: 'chat.channel', tone: 'secondary' }] }),
  screen('profile.main', 'Профиль', 'Профиль', 'Личные данные и безопасность аккаунта.', everyone, 'card', { nativeRoute: 'clientProfile', rows: [row('Способы входа', 'Пароль и код из письма', undefined, 'Открыть', 'profile.auth-methods'), row('Юридические документы', 'Условия и политика', undefined, 'Открыть', 'profile.legal'), row('Удаление аккаунта', 'Запрос и статус', undefined, 'Открыть', 'profile.delete')], actions: [{ label: 'Изменить профиль', target: 'profile.edit' }] }),
  screen('profile.edit', 'Профиль', 'Изменить профиль', 'Фото, имя, фамилия и день рождения.', everyone, 'sheet', { fields: ['Фото', 'Имя', 'Фамилия', 'День рождения'], actions: [{ label: 'Сохранить', target: 'profile.main' }, { label: 'Отмена', target: 'profile.main', tone: 'secondary' }] }),
  screen('profile.avatar', 'Профиль', 'Обрезать фотографию', 'Масштаб и область нового фото.', everyone, 'dialog', { actions: [{ label: 'Применить', target: 'profile.edit' }, { label: 'Отмена', target: 'profile.edit', tone: 'secondary' }] }),
  screen('profile.auth-methods', 'Профиль', 'Способы входа', 'Пароль, код из письма и адрес почты.', everyone, 'card', { rows: [row('Пароль', 'Установлен', undefined, 'Изменить', 'profile.password'), row('Код из письма для входа', 'Доступен', undefined, 'Настроено', 'profile.email'), row('Электронная почта', 'alina@example.ru', undefined, 'Изменить', 'profile.email')] }),
  screen('profile.password', 'Профиль', 'Изменить пароль', 'Текущий и новый пароль.', everyone, 'form', { fields: ['Текущий пароль', 'Новый пароль', 'Повторите пароль'], actions: [{ label: 'Сохранить пароль', target: 'profile.auth-methods' }, { label: 'Отмена', target: 'profile.auth-methods', tone: 'secondary' }] }),
  screen('profile.email', 'Профиль', 'Изменить почту', 'Новый адрес и подтверждение выхода.', everyone, 'form', { fields: ['Новая электронная почта', 'Текущий пароль'], actions: [{ label: 'Изменить почту и выйти', target: 'auth.login' }, { label: 'Отмена', target: 'profile.auth-methods', tone: 'secondary' }] }),
  screen('profile.legal', 'Профиль', 'Юридические документы', 'Актуальные документы и даты редакций.', everyone, 'list', { rows: [row('Пользовательское соглашение', 'Редакция от 12.08.2026', undefined, 'Открыть', 'auth.consent.document'), row('Политика конфиденциальности', 'Редакция от 12.08.2026', undefined, 'Открыть', 'auth.consent.document')] }),
  screen('profile.delete', 'Профиль', 'Удаление аккаунта', 'Запрос, срок обработки и последствия.', everyone, 'form', { fields: ['Причина', 'Подтверждаю запрос'], actions: [{ label: 'Отправить запрос', target: 'profile.delete.status', tone: 'danger' }, { label: 'Отмена', target: 'profile.main', tone: 'secondary' }] }),
  screen('profile.delete.status', 'Профиль', 'Запрос на удаление', 'Состояние и возможность отозвать запрос.', everyone, 'state', { metrics: [{ label: 'Состояние', value: 'На проверке' }, { label: 'Создан', value: '16 августа' }, { label: 'Срок', value: '30 августа' }], actions: [{ label: 'Отозвать запрос', target: 'profile.delete.revoke' }, { label: 'Выйти', target: 'auth.login', tone: 'secondary' }] }),
  screen('profile.delete.revoke', 'Профиль', 'Отозвать запрос?', 'Запрос на удаление будет отменён.', everyone, 'dialog', { actions: [{ label: 'Отозвать', target: 'profile.main' }, { label: 'Оставить запрос', target: 'profile.delete.status', tone: 'secondary' }] }),
]

const systemScreens: ScreenDefinition[] = [
  screen('system.updates', 'Системные экраны', 'Обновления', 'Текущая версия и полная история выпусков.', everyone, 'update', { rows: [row('Версия 1.5.15', 'Расписание и обновления', '16 августа 2026', 'Доступно', 'system.update.available'), row('Версия 1.5.14', 'Оплаты и абонементы', '15 августа 2026', 'Установлено', 'system.update.notes')] }),
  screen('system.update.available', 'Системные экраны', 'Доступно обновление', 'Новая версия готова к автоматической установке.', everyone, 'dialog', { notes: ['Приложение закроется, обновится и запустится снова.'], actions: [{ label: 'Обновить и перезапустить', target: 'system.update.installing' }, { label: 'Позже', target: 'system.updates', tone: 'secondary' }] }),
  screen('system.update.installing', 'Системные экраны', 'Установка обновления', 'Загрузка, проверка и перезапуск приложения.', everyone, 'state', { state: 'loading', actions: [{ label: 'Показать результат', target: 'system.update.installed' }] }),
  screen('system.update.installed', 'Системные экраны', 'Обновление установлено', 'Приложение работает на новой версии.', everyone, 'state', { actions: [{ label: 'Открыть приложение', target: 'overview.main' }, { label: 'Что изменилось', target: 'system.update.notes', tone: 'secondary' }] }),
  screen('system.update.notes', 'Системные экраны', 'Что изменилось', 'Полное описание улучшений выбранной версии.', everyone, 'update', { notes: ['Улучшена проверка конфликтов при создании занятий.', 'Версия приложения всегда видна слева внизу.', 'Исправлены понятные сообщения об ошибках.'], actions: [{ label: 'Назад к обновлениям', target: 'system.updates' }] }),
  screen('system.notifications', 'Системные экраны', 'Уведомления', 'Новые события задач, расписания и оплат.', everyone, 'list', { rows: [row('Конфликт расписания', 'Аудитория 1 занята', '5 минут назад', 'Новое', 'schedule.conflict.inspector'), row('Новая задача', 'Позвонить по заявке с сайта', '12 минут назад', 'Новое', 'tasks.detail')] }),
  screen('system.command', 'Системные экраны', 'Открыть раздел', 'Быстрый поиск доступных разделов.', everyone, 'dialog', { fields: ['Название раздела'], rows: [row('Расписание', 'Неделя и день', undefined, 'Открыть', 'schedule.week'), row('Клиенты', 'Лиды и ученики', undefined, 'Открыть', 'clients.leads'), row('Настройки', 'Настройки системы', undefined, 'Открыть', 'settings.root')] }),
  screen('state.loading', 'Системные состояния', 'Загрузка данных', 'Скелетон страницы во время получения данных.', everyone, 'state', { state: 'loading', actions: [{ label: 'Показать данные', target: 'overview.main' }] }),
  screen('state.empty', 'Системные состояния', 'Здесь пока ничего нет', 'Пустое состояние с понятным следующим действием.', everyone, 'state', { state: 'empty', actions: [{ label: 'Создать запись', target: 'tasks.create' }] }),
  screen('state.error', 'Системные состояния', 'Не удалось загрузить данные', 'Понятная ошибка и безопасный повтор.', everyone, 'state', { state: 'error', actions: [{ label: 'Повторить', target: 'overview.main' }] }),
  screen('state.forbidden', 'Системные состояния', 'Нет доступа', 'Роль не позволяет открыть этот раздел.', everyone, 'state', { state: 'forbidden', actions: [{ label: 'Вернуться', target: 'overview.main' }] }),
  screen('state.offline', 'Системные состояния', 'Нет подключения', 'Данные не обновляются без сети.', everyone, 'state', { state: 'error', actions: [{ label: 'Проверить снова', target: 'overview.main' }] }),
  screen('state.unsaved', 'Системные состояния', 'Несохранённые изменения', 'Подтверждение ухода из формы.', everyone, 'dialog', { actions: [{ label: 'Остаться', target: 'clients.student.card' }, { label: 'Закрыть без сохранения', target: 'clients.students', tone: 'danger' }] }),
]

export const screenManifest: ScreenDefinition[] = [
  ...authScreens,
  ...coreScreens,
  ...scheduleScreens,
  ...clientManagementScreens,
  ...portalScreens,
  ...teacherScreens,
  ...analyticsScreens,
  ...settingsScreens,
  ...chatAndProfileScreens,
  ...systemScreens,
]

export const screenById = new Map(screenManifest.map((item) => [item.id, item]))
export const screenGroups = [...new Set(screenManifest.map((item) => item.group))]

export function validateScreenManifest() {
  const ids = new Set<string>()
  const duplicateIds: string[] = []
  const brokenTargets: Array<{ from: string; target: string }> = []

  for (const item of screenManifest) {
    if (ids.has(item.id)) duplicateIds.push(item.id)
    ids.add(item.id)
  }
  for (const item of screenManifest) {
    const targets = [
      ...(item.actions ?? []).map((action) => action.target),
      ...(item.tabs ?? []).map((tab) => tab.target),
      ...(item.rows ?? []).flatMap((entry) => entry.target ? [entry.target] : []),
    ]
    for (const target of targets) {
      if (!ids.has(target)) brokenTargets.push({ from: item.id, target })
    }
  }

  return { total: screenManifest.length, unique: ids.size, duplicateIds, brokenTargets, valid: duplicateIds.length === 0 && brokenTargets.length === 0 }
}

export function withState(entry: ScreenDefinition, state: ScreenState): ScreenDefinition {
  if (state === 'content') return entry
  return { ...entry, state, id: entry.id, actions: [{ label: state === 'loading' ? 'Показать данные' : 'Повторить', target: entry.id }] }
}
