-- MagicMusicCRM v2 storage, FCM token and notification dispatch hardening.
--
-- Covers:
-- - Private chat attachments with RLS-bound signed URL access.
-- - Owner-scoped avatar writes.
-- - FCM tokens moved out of broadly readable profiles into guarded storage.
-- - Notification Edge Function dispatch guarded by a Vault-backed shared secret.

begin;

-- ── FCM token boundary ─────────────────────────────────────────────────────

create table if not exists public.fcm_tokens (
  id bigint primary key generated by default as identity,
  user_id uuid not null references public.profiles(id) on delete cascade,
  token text not null,
  platform text,
  updated_at timestamptz not null default now()
);

do $$
begin
  if exists (
    select 1
    from information_schema.columns
    where table_schema = 'public'
      and table_name = 'fcm_tokens'
      and column_name = 'id'
      and identity_generation is null
      and column_default is null
  ) then
    alter table public.fcm_tokens alter column id add generated by default as identity;
  end if;
end;
$$;

alter table public.fcm_tokens
  add column if not exists platform text;

alter table public.fcm_tokens
  alter column updated_at set default now();

create unique index if not exists fcm_tokens_one_token_per_user
on public.fcm_tokens (user_id, token);

alter table public.fcm_tokens enable row level security;

revoke all on table public.fcm_tokens from public, anon, authenticated;
grant select, insert, update, delete on table public.fcm_tokens to authenticated;
grant all on table public.fcm_tokens to service_role;

drop policy if exists "Staff can do all on fcm_tokens" on public.fcm_tokens;
create policy "Staff can do all on fcm_tokens"
on public.fcm_tokens
for all
to authenticated
using (private.user_role() in ('admin'::public.user_role, 'manager'::public.user_role))
with check (private.user_role() in ('admin'::public.user_role, 'manager'::public.user_role));

insert into public.fcm_tokens (user_id, token, platform, updated_at)
select distinct on (fcm_token) id, fcm_token, null, now()
from public.profiles
where nullif(trim(coalesce(fcm_token, '')), '') is not null
order by fcm_token, last_seen_at desc nulls last, created_at desc nulls last
on conflict (token) do update
set user_id = excluded.user_id,
    updated_at = excluded.updated_at;

create or replace function private.upsert_fcm_token(
  p_token text,
  p_platform text default null
)
returns void
language plpgsql
security definer
set search_path = public, private
as $function$
begin
  if auth.uid() is null then
    raise exception 'not authorized' using errcode = '42501';
  end if;

  if nullif(trim(coalesce(p_token, '')), '') is null or length(p_token) > 4096 then
    raise exception 'invalid FCM token' using errcode = '22023';
  end if;

  insert into public.fcm_tokens (user_id, token, platform, updated_at)
  values (auth.uid(), trim(p_token), nullif(trim(coalesce(p_platform, '')), ''), now())
  on conflict (token) do update
  set user_id = excluded.user_id,
      platform = coalesce(excluded.platform, public.fcm_tokens.platform),
      updated_at = now();

  update public.profiles
  set fcm_token = null
  where id = auth.uid();
end;
$function$;

revoke execute on function private.upsert_fcm_token(text, text) from public, anon;
grant execute on function private.upsert_fcm_token(text, text) to authenticated;

create or replace function public.upsert_fcm_token(
  p_token text,
  p_platform text default null
)
returns void
language sql
security invoker
set search_path = public, private
as $function$
  select private.upsert_fcm_token(p_token, p_platform);
$function$;

revoke execute on function public.upsert_fcm_token(text, text) from public, anon;
grant execute on function public.upsert_fcm_token(text, text) to authenticated;

update public.profiles
set fcm_token = null
where fcm_token is not null;

revoke update on table public.profiles from public, anon, authenticated;
grant update (first_name, last_name, phone, dob, avatar_url, last_seen_at, profile_completed_at)
on table public.profiles to authenticated;

-- ── Storage boundary ───────────────────────────────────────────────────────

update storage.buckets
set public = false,
    file_size_limit = 26214400
where id = 'chat-attachments';

update storage.buckets
set public = true
where id = 'avatars';

drop policy if exists "Authenticated users can upload chat attachments" on storage.objects;
drop policy if exists "Users can delete their own chat attachments" on storage.objects;
drop policy if exists "Users can upload avatars" on storage.objects;
drop policy if exists "Users can update avatars" on storage.objects;
drop policy if exists "Users can delete avatars" on storage.objects;
drop policy if exists "Chat attachment owners can upload" on storage.objects;
drop policy if exists "Chat attachment participants can read" on storage.objects;
drop policy if exists "Chat attachment owners and staff can delete" on storage.objects;
drop policy if exists "Avatar owners can upload" on storage.objects;
drop policy if exists "Avatar owners and staff can update" on storage.objects;
drop policy if exists "Avatar owners and staff can delete" on storage.objects;

create policy "Chat attachment owners can upload"
on storage.objects
for insert
to authenticated
with check (
  bucket_id = 'chat-attachments'
  and (storage.foldername(name))[1] = auth.uid()::text
);

create policy "Chat attachment participants can read"
on storage.objects
for select
to authenticated
using (
  bucket_id = 'chat-attachments'
  and (
    (storage.foldername(name))[1] = auth.uid()::text
    or private.user_role() in ('admin'::public.user_role, 'manager'::public.user_role)
    or exists (
      select 1
      from public.messages m
      where (
          m.attachment_url = 'storage://chat-attachments/' || storage.objects.name
          or m.attachment_url like '%/storage/v1/object/public/chat-attachments/' || storage.objects.name
        )
        and (
          m.sender_id = auth.uid()
          or m.receiver_id = auth.uid()
          or (m.group_chat_id is not null and private.is_group_member(m.group_chat_id))
        )
    )
  )
);

create policy "Chat attachment owners and staff can delete"
on storage.objects
for delete
to authenticated
using (
  bucket_id = 'chat-attachments'
  and (
    (storage.foldername(name))[1] = auth.uid()::text
    or private.user_role() in ('admin'::public.user_role, 'manager'::public.user_role)
  )
);

create policy "Avatar owners can upload"
on storage.objects
for insert
to authenticated
with check (
  bucket_id = 'avatars'
  and (storage.foldername(name))[1] = auth.uid()::text
);

create policy "Avatar owners and staff can update"
on storage.objects
for update
to authenticated
using (
  bucket_id = 'avatars'
  and (
    (storage.foldername(name))[1] = auth.uid()::text
    or private.user_role() in ('admin'::public.user_role, 'manager'::public.user_role)
  )
)
with check (
  bucket_id = 'avatars'
  and (
    (storage.foldername(name))[1] = auth.uid()::text
    or private.user_role() in ('admin'::public.user_role, 'manager'::public.user_role)
  )
);

create policy "Avatar owners and staff can delete"
on storage.objects
for delete
to authenticated
using (
  bucket_id = 'avatars'
  and (
    (storage.foldername(name))[1] = auth.uid()::text
    or private.user_role() in ('admin'::public.user_role, 'manager'::public.user_role)
  )
);

-- ── Notification dispatch guard ────────────────────────────────────────────

create or replace function public.trigger_invoke_send_notification()
returns trigger
language plpgsql
security definer
set search_path = public, vault
as $function$
declare
  v_user_ids uuid[];
  v_url text;
  v_anon_key text;
  v_dispatch_secret text;
  v_payload jsonb;
  v_target_chat_id text;
begin
  v_target_chat_id := coalesce(new.data->>'chat_id', new.data->>'sender_id');

  if new.data->>'receiver_id' is not null then
    select array_agg(id) into v_user_ids
    from (select (new.data->>'receiver_id')::uuid as id) sub
    where not exists (
      select 1
      from public.chat_preferences cp
      where cp.user_id = sub.id
        and cp.chat_id = v_target_chat_id
        and cp.is_muted = true
    );
  else
    select array_agg(p.id) into v_user_ids
    from public.profiles p
    where p.role::text = any(new.target_roles)
      and not exists (
        select 1
        from public.chat_preferences cp
        where cp.user_id = p.id
          and cp.chat_id = v_target_chat_id
          and cp.is_muted = true
      );
  end if;

  if v_user_ids is null or array_length(v_user_ids, 1) = 0 then
    return new;
  end if;

  select decrypted_secret into v_dispatch_secret
  from vault.decrypted_secrets
  where name = 'notification_dispatch_secret'
  limit 1;

  if nullif(v_dispatch_secret, '') is null then
    return new;
  end if;

  v_payload := jsonb_build_object(
    'userIds', v_user_ids,
    'title', new.data->>'title',
    'body', new.data->>'body',
    'sender_id', new.data->>'sender_id',
    'chat_id', new.data->>'chat_id',
    'receiver_id', new.data->>'receiver_id'
  );

  v_url := 'https://api.magic-music.org/functions/v1/send-notification';
  v_anon_key := 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhibHBueXdubGhmZ29mc2tiZHhiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzMxNDA5ODcsImV4cCI6MjA4ODcxNjk4N30.qRuC_TQ8rlz68fzi0geqqdbkA7ABRBEyw3GyMkMJJxg';

  perform net.http_post(
    url := v_url,
    headers := jsonb_build_object(
      'Content-Type', 'application/json',
      'Authorization', 'Bearer ' || v_anon_key,
      'x-notification-dispatch-secret', v_dispatch_secret
    ),
    body := v_payload
  );

  return new;
end;
$function$;

revoke execute on function public.trigger_invoke_send_notification() from public, anon, authenticated;

commit;
